// Contenu des pages d'anniversaire (fr, en, de). Voir src/lib/occasions.js.
export const ANNIVERSAIRES = {
  'anniversaire': {
    fr: {
      titre: 'Appareil photo jetable anniversaire, sans appli',
      description: 'L’appareil photo jetable d’anniversaire sur le téléphone de vos invités : un QR code, des clichés comptés, et toutes les photos révélées le lendemain.',
      eyebrow: 'Anniversaire · appareil photo jetable',
      h1: 'L’appareil photo jetable de votre anniversaire, dans la poche de chaque invité',
      intro: [
        'Le soir d’un anniversaire, tout le monde sort son téléphone, et le lendemain personne n’a les photos des autres. Elles dorment dans quarante pellicules différentes, quelques-unes passent dans un groupe de discussion, la plupart ne sortent jamais. Vous, la personne fêtée, êtes celle qui en a le moins.',
        'Time to Flash change le téléphone de chaque invité en appareil photo jetable partagé. Un QR code sur la table, un scan, et l’appareil s’ouvre dans le navigateur, sans application ni compte. Chacun a quelques clichés, personne ne voit rien pendant la fête, et toutes les photos apparaissent ensemble à l’heure que vous avez choisie.',
      ],
      ticks: ['Aucune application à installer', 'Gratuit jusqu’à 5 invités', 'Photos révélées le lendemain'],
      pourquoiTitre: 'Pourquoi un jetable partagé pour un anniversaire',
      pourquoiSous: 'Une fête d’anniversaire, c’est une soirée où l’on veut tout garder sans passer la nuit derrière un écran.',
      pourquoi: [
        { ic: '🎂', t: 'La personne fêtée a enfin ses photos', s: 'Celui ou celle qu’on fête est la personne qui photographie le moins de la soirée. Avec un album commun, elle récupère d’un coup ce que tous ses invités ont vu.' },
        { ic: '🎞️', t: 'Un jeu, pas une corvée', s: 'Avec quelques clichés seulement, chaque photo compte, et on se demande ce qui mérite d’être pris. Ça fait parler, ça fait rire, et ça devient une animation à part entière.' },
        { ic: '🎁', t: 'Un deuxième cadeau le lendemain', s: 'La fête est finie, et le lendemain toutes les photos arrivent en même temps. C’est le moment où l’on revit la soirée, souvent avec plus d’émotion que sur le coup.' },
      ],
      etapes: [
        { t: 'Posez l’affiche près du gâteau ou du bar', s: 'Créez l’événement en deux minutes et imprimez l’affiche avec son QR code. Posez-la là où tout le monde passe : à côté des boissons, sur la table du buffet, ou à l’entrée.' },
        { t: 'Chacun a ses clichés comptés', s: 'Vous choisissez le nombre de photos par invité, de 3 à 15. Les photos partent dans l’album sans qu’on puisse les regarder : comme avec un vrai jetable, on vise et on espère.' },
        { t: 'La révélation le lendemain midi', s: 'Programmez la révélation pour le lendemain, vers midi, quand tout le monde a dormi. Les invités reçoivent un lien et découvrent l’album en même temps que vous.' },
      ],
      ideesTitre: 'Idées d’animation photo pour un anniversaire',
      ideesSous: 'Quelques idées simples pour que les photos racontent vraiment la fête, quel que soit l’âge.',
      idees: [
        { t: 'Le défi « une photo avec la personne fêtée »', s: 'Lancez la règle en début de soirée : chaque invité doit garder un cliché pour une photo avec la personne qu’on fête. À la fin, vous avez son portrait avec chacun de ses proches, ce qu’aucun photographe n’aurait le temps de faire. C’est souvent la série la plus touchante de l’album.' },
        { t: 'La photo du gâteau, vue par tout le monde', s: 'Au moment des bougies, demandez à chacun de prendre le gâteau depuis là où il est. Le lendemain, vous découvrez la même scène sous vingt angles différents : le souffle, les visages éclairés par les bougies, le cousin qui filme au lieu de chanter.' },
        { t: 'Le mur des portraits à l’entrée', s: 'Collez une feuille de couleur ou un drap au mur avec un éclairage simple, et proposez à chaque arrivant de se faire photographier par l’invité précédent. Le portrait passe de main en main. En fin d’album, vous avez une galerie de toutes les personnes présentes, dans l’ordre d’arrivée.' },
        { t: 'Les missions photo dans un chapeau', s: 'Écrivez sur des petits papiers des missions courtes : « le plus grand fou rire », « deux personnes qui ne se connaissaient pas », « un détail de la déco », « quelqu’un qui danse mal ». Chaque invité en tire une en arrivant. Ça brise la glace entre les différents cercles d’amis.' },
        { t: 'Une pellicule pour les 18 ans, une autre pour les 60', s: 'Le principe marche à tout âge, il suffit d’ajuster. Pour des 18 ans, laissez les ados jouer avec peu de clichés, ils s’en souviendront. Pour des 60 ans, misez sur les photos de famille et le passage du QR code d’une génération à l’autre.' },
        { t: 'La surprise party sans fuite', s: 'Pour une fête surprise, créez l’album à l’avance et envoyez le lien aux invités en leur demandant de ne pas le partager. Le premier cliché de la soirée doit être la tête de la personne fêtée quand elle entre. Prévenez tout le monde pour qu’il y ait dix téléphones prêts.' },
        { t: 'Le rendu jetable avec la date incrustée', s: 'Dans l’album, choisissez la pellicule « Jetable » : couleurs chaudes, grain, et la date incrustée dans le coin comme sur les photos d’autrefois. Pour un anniversaire, la date en orange dans l’angle fait tout de suite souvenir, et elle reste dans les photos téléchargées.' },
        { t: 'Le tirage pour le livre d’or', s: 'Plutôt qu’un livre d’or où l’on écrit trois mots pressés, faites imprimer une sélection de photos après la révélation et demandez aux invités d’écrire un mot au dos à la prochaine occasion. Les tirages papier se commandent directement depuis l’album.' },
      ],
      conseilsTitre: 'Nos conseils pour réussir l’album de votre anniversaire',
      conseils: [
        'Combien de clichés donner ? Pour une soirée de 20 à 30 invités, 8 à 10 photos par personne donnent un album riche sans être interminable : vous récupérez deux à trois cents images. Au-delà de 40 invités, descendez à 5 ou 6 clichés : l’album reste lisible, et chacun choisit vraiment ses moments. Si quelqu’un a tout utilisé avant le gâteau, vous pouvez recharger sa pellicule.',
        'À quelle heure révéler ? Le lendemain vers midi est le bon moment pour une fête du soir : tout le monde a dormi, et l’album arrive au moment où l’on commence à se raconter la veille. Pour un anniversaire en journée (un déjeuner de famille, un goûter), révélez le soir même vers 21 h, une fois les invités rentrés chez eux.',
        'Quelle formule choisir ? Un anniversaire réunit le plus souvent entre 15 et 60 personnes. Jusqu’à 30 participants, la formule à 4,99 € suffit ; jusqu’à 50, comptez 14,99 € ; et pour une grande fête, la formule 100 coûte 29,99 €. C’est un paiement unique, sans abonnement. Vous pouvez aussi tester gratuitement avec 5 personnes, sans carte bancaire, avant de vous décider.',
      ],
      faq: [
        { q: 'Mes invités doivent-ils télécharger une application ?', a: 'Non. Ils scannent le QR code avec l’appareil photo de leur téléphone, et l’appareil Time to Flash s’ouvre dans le navigateur. Pas d’application, pas de compte, juste un prénom à saisir. Une application iPhone existe pour ceux qui la préfèrent, mais elle est facultative.' },
        { q: 'Combien coûte un appareil photo jetable d’anniversaire avec Time to Flash ?', a: 'C’est gratuit jusqu’à 5 participants. Ensuite c’est un paiement unique selon le nombre d’invités : 1,99 € pour 10, 4,99 € pour 30, 14,99 € pour 50, 29,99 € pour 100. Pas d’abonnement, et le téléchargement de l’album est compris.' },
        { q: 'Est-ce adapté aux enfants et aux invités âgés ?', a: 'Oui, c’est même pensé pour ça : un scan et un bouton pour photographier, rien d’autre à comprendre. Les grands-parents peuvent se faire aider pour le scan, ensuite l’appareil se manie seul. Les enfants adorent le côté jetable, et le nombre de clichés compté évite les cent photos du même chien.' },
        { q: 'Et si un invité n’a pas de téléphone ou pas de réseau ?', a: 'Un invité sans téléphone peut emprunter celui d’un proche et prendre ses photos sous son propre prénom. Si le réseau coupe, la photo est gardée dans le téléphone et part toute seule dès que la connexion revient. Pour une salle mal couverte, affichez le code wifi à côté du QR code.' },
        { q: 'Peut-on l’utiliser pour une fête surprise ?', a: 'Oui. Créez l’événement à l’avance, envoyez le lien aux invités sans que la personne fêtée le voie, et posez l’affiche au dernier moment. Vous pouvez aussi ajouter un co-organisateur pour partager la préparation, et masquer avant la révélation une photo qui en dirait trop.' },
      ],
      ctaTitre: 'Offrez-vous les photos de toute la fête',
      ctaSous: 'Créez votre appareil photo jetable d’anniversaire en deux minutes. Gratuit jusqu’à 5 invités.',
    },
    en: {
      titre: 'Disposable camera for a birthday party, no app',
      description: 'A disposable camera for your birthday party on every guest’s phone: one QR code, a few shots each, and every photo revealed the next morning.',
      eyebrow: 'Birthday · disposable camera',
      h1: 'A disposable camera for your birthday party, in every guest’s pocket',
      intro: [
        'At every birthday party, everyone gets their phone out, and the next day nobody has anyone else’s photos. They sit in forty different camera rolls, a handful land in a group chat, most never see daylight. And you, the person being celebrated, end up with the fewest of all.',
        'Time to Flash turns every guest’s phone into a shared disposable camera. A QR code on the table, one scan, and the camera opens in the browser, with no app and no account. Everyone gets a few shots, nobody sees anything during the party, and all the photos appear together at the time you pick.',
      ],
      ticks: ['Nothing to install', 'Free for up to 5 guests', 'Photos revealed the next day'],
      pourquoiTitre: 'Why a shared disposable suits a birthday',
      pourquoiSous: 'A birthday is a night you want to remember without spending it behind a screen.',
      pourquoi: [
        { ic: '🎂', t: 'The birthday person finally gets the photos', s: 'Whoever’s birthday it is takes the fewest pictures all night. With one shared album, they get everything their guests saw, all at once.' },
        { ic: '🎞️', t: 'A game, not a chore', s: 'With only a few shots each, every photo matters, and people start choosing what deserves one. It gets everyone talking and laughing, and it becomes part of the entertainment.' },
        { ic: '🎁', t: 'A second present the next day', s: 'The party’s over, then every photo lands at once the following day. That’s when people relive the night, often with more feeling than in the moment.' },
      ],
      etapes: [
        { t: 'Put the poster by the cake or the bar', s: 'Create the event in two minutes and print the poster with its QR code. Put it where everyone goes: next to the drinks, on the buffet table, or by the door.' },
        { t: 'Everyone gets a set number of shots', s: 'You choose how many photos each guest gets, from 3 to 15. Photos go straight to the album and can’t be viewed: just like a real disposable, you aim and hope for the best.' },
        { t: 'The reveal at lunchtime the next day', s: 'Schedule the reveal for the next day, around noon, once everyone has slept. Guests get a link and discover the album at the same moment you do.' },
      ],
      ideesTitre: 'Photo ideas for a birthday party',
      ideesSous: 'A few simple ideas so the photos really tell the story of the party, whatever the age.',
      idees: [
        { t: 'The “one photo with the birthday star” challenge', s: 'Set the rule early on: every guest saves one shot for a photo with the person being celebrated. By the end you have their portrait with each of the people who matter to them, which no photographer would have time to do. It is often the most moving set in the album.' },
        { t: 'The cake, from every angle', s: 'When the candles come out, ask everyone to photograph the cake from wherever they are standing. The next day you get the same moment from twenty viewpoints: the big blow, faces lit by candlelight, the cousin filming instead of singing.' },
        { t: 'A portrait wall at the door', s: 'Pin a coloured sheet or a plain cloth to a wall with some simple lighting, and ask each new arrival to be photographed by the guest before them. The portrait gets passed along. At the end of the album you have a gallery of everyone who came, in order of arrival.' },
        { t: 'Photo missions out of a hat', s: 'Write short missions on slips of paper: “the biggest laugh”, “two people who have never met”, “a detail of the decorations”, “someone dancing badly”. Each guest picks one on arrival. It gets different groups of friends mixing.' },
        { t: 'One film for an 18th, another for a 60th', s: 'The idea works at any age; you just adjust it. For an 18th, let the teenagers play with only a few shots, they will remember it. For a 60th, focus on family photos and the QR code being passed from one generation to the next.' },
        { t: 'A surprise party with no leaks', s: 'For a surprise party, create the album in advance and send the link to guests, asking them not to share it. The first shot of the night should be the birthday person’s face as they walk in. Warn everyone, so there are ten phones ready.' },
        { t: 'The disposable look with the date stamp', s: 'In the album, pick the “Disposable” film: warm colours, grain, and the date printed in the corner like old holiday snaps. For a birthday, that orange date in the corner instantly feels like a memory, and it stays in the downloaded photos.' },
        { t: 'Prints for the guest book', s: 'Instead of a guest book full of rushed three-word messages, print a selection of photos after the reveal and ask guests to write on the back next time you see them. Prints can be ordered straight from the album.' },
      ],
      conseilsTitre: 'Our tips for a great birthday album',
      conseils: [
        'How many shots to give? For a party of 20 to 30 guests, 8 to 10 photos each makes a full album without it dragging on: you end up with two or three hundred pictures. Above 40 guests, go down to 5 or 6 shots each, so the album stays easy to browse and everyone really picks their moments. If someone runs out before the cake, you can top up their film.',
        'When to reveal? For an evening party, around noon the next day is ideal: everyone has slept, and the album arrives just as people start swapping stories about the night before. For a daytime birthday (a family lunch, an afternoon party), reveal the same evening around 9pm, once guests are home.',
        'Which plan to choose? Most birthdays bring together 15 to 60 people. Up to 30 guests, the €4.99 plan is enough; up to 50, it is €14.99; and for a big party, the 100 plan costs €29.99. It is a one-off payment, with no subscription. You can also try it free with 5 people, no card needed, before you decide.',
      ],
      faq: [
        { q: 'Do my guests need to download an app?', a: 'No. They scan the QR code with their phone’s camera and the Time to Flash camera opens in the browser. No app, no account, just a first name to type. There is an iPhone app for anyone who prefers it, but it is optional.' },
        { q: 'How much does a birthday disposable camera cost with Time to Flash?', a: 'It is free for up to 5 people. After that it is a one-off payment based on the number of guests: €1.99 for 10, €4.99 for 30, €14.99 for 50, €29.99 for 100. No subscription, and downloading the album is included.' },
        { q: 'Does it work for children and older guests?', a: 'Yes, it is designed for exactly that: one scan, one button to take a photo, nothing else to figure out. Grandparents may want a hand with the scan, then the camera is easy on its own. Children love the disposable idea, and the limited shots spare you a hundred photos of the dog.' },
        { q: 'What if a guest has no phone or no signal?', a: 'A guest without a phone can borrow someone else’s and take photos under their own name. If the signal drops, the photo is kept on the phone and sends itself as soon as the connection is back. In a venue with poor coverage, put the Wi-Fi password next to the QR code.' },
        { q: 'Can I use it for a surprise party?', a: 'Yes. Create the event in advance, send the link to guests without the birthday person seeing it, and put the poster out at the last minute. You can add a co-organiser to share the planning, and hide any photo that gives too much away before the reveal.' },
      ],
      ctaTitre: 'Get the photos from the whole party',
      ctaSous: 'Set up your birthday disposable camera in two minutes. Free for up to 5 guests.',
    },
    de: {
      titre: 'Digitale Einwegkamera zum Geburtstag, ganz ohne App',
      description: 'Die Einwegkamera für Ihren Geburtstag auf dem Handy jedes Gastes: ein QR-Code, begrenzte Aufnahmen und alle Fotos am nächsten Morgen für alle sichtbar.',
      eyebrow: 'Geburtstag · Einwegkamera',
      h1: 'Die digitale Einwegkamera für Ihren Geburtstag, in der Tasche jedes Gastes',
      intro: [
        'Auf jeder Geburtstagsfeier zücken alle ihr Handy, und am nächsten Tag hat niemand die Fotos der anderen. Sie liegen in vierzig verschiedenen Galerien, ein paar landen in einem Gruppenchat, die meisten sieht nie wieder jemand. Und ausgerechnet Sie, das Geburtstagskind, haben am Ende die wenigsten.',
        'Time to Flash macht aus dem Handy jedes Gastes eine gemeinsame Einwegkamera. Ein QR-Code auf dem Tisch, einmal scannen, und die Kamera öffnet sich im Browser, ohne App und ohne Konto. Jeder hat ein paar Aufnahmen, während der Feier sieht niemand etwas, und alle Fotos erscheinen gemeinsam zu der Uhrzeit, die Sie festlegen.',
      ],
      ticks: ['Keine App nötig', 'Bis 5 Gäste kostenlos', 'Fotos am nächsten Tag präsentiert'],
      pourquoiTitre: 'Warum eine gemeinsame Einwegkamera zum Geburtstag passt',
      pourquoiSous: 'Einen Geburtstag will man festhalten, ohne den ganzen Abend hinter dem Bildschirm zu verbringen.',
      pourquoi: [
        { ic: '🎂', t: 'Das Geburtstagskind bekommt endlich seine Fotos', s: 'Wer gefeiert wird, fotografiert selbst am wenigsten. Mit einem gemeinsamen Album bekommt es auf einen Schlag alles, was die Gäste gesehen haben.' },
        { ic: '🎞️', t: 'Ein Spiel, keine Pflicht', s: 'Mit nur wenigen Aufnahmen zählt jedes Bild, und man überlegt, was ein Foto wert ist. Das sorgt für Gesprächsstoff und Gelächter und wird zu einem eigenen Programmpunkt.' },
        { ic: '🎁', t: 'Ein zweites Geschenk am nächsten Tag', s: 'Die Feier ist vorbei, und am nächsten Tag kommen alle Fotos gleichzeitig. Dann erlebt man den Abend noch einmal, oft bewegender als im Moment selbst.' },
      ],
      etapes: [
        { t: 'Das Plakat neben die Torte oder an die Bar', s: 'Erstellen Sie das Event in zwei Minuten und drucken Sie das Plakat mit dem QR-Code. Stellen Sie es dorthin, wo alle vorbeikommen: neben die Getränke, auf das Buffet oder an den Eingang.' },
        { t: 'Jeder hat eine begrenzte Zahl an Aufnahmen', s: 'Sie legen fest, wie viele Fotos jeder Gast machen darf, zwischen 3 und 15. Die Bilder gehen direkt ins Album und lassen sich nicht ansehen: Wie bei einer echten Einwegkamera zielt man und hofft das Beste.' },
        { t: 'Die Präsentation am nächsten Mittag', s: 'Planen Sie die Präsentation für den nächsten Tag gegen Mittag, wenn alle ausgeschlafen sind. Die Gäste bekommen einen Link und entdecken das Album im selben Moment wie Sie.' },
      ],
      ideesTitre: 'Fotoideen für die Geburtstagsfeier',
      ideesSous: 'Ein paar einfache Ideen, damit die Fotos wirklich die Geschichte der Feier erzählen, egal in welchem Alter.',
      idees: [
        { t: 'Die Challenge „ein Foto mit dem Geburtstagskind“', s: 'Verkünden Sie die Regel gleich zu Beginn: Jeder Gast hebt sich eine Aufnahme für ein Foto mit dem Geburtstagskind auf. Am Ende haben Sie ein Porträt mit jedem einzelnen Gast, wofür kein Fotograf Zeit hätte. Oft ist das die berührendste Serie im ganzen Album.' },
        { t: 'Die Torte aus allen Blickwinkeln', s: 'Wenn die Kerzen brennen, bitten Sie alle, die Torte von ihrem Platz aus zu fotografieren. Am nächsten Tag sehen Sie denselben Moment aus zwanzig Perspektiven: das Auspusten, die Gesichter im Kerzenlicht, den Cousin, der filmt statt singt.' },
        { t: 'Die Porträtwand am Eingang', s: 'Hängen Sie ein farbiges Tuch an die Wand, sorgen Sie für einfaches Licht und bitten Sie jeden Neuankömmling, sich vom vorherigen Gast fotografieren zu lassen. So wandert das Porträt von Hand zu Hand. Am Ende haben Sie eine Galerie aller Gäste, in der Reihenfolge ihrer Ankunft.' },
        { t: 'Fotoaufgaben aus dem Hut', s: 'Schreiben Sie kurze Aufgaben auf Zettel: „der lauteste Lacher“, „zwei, die sich noch nicht kannten“, „ein Detail der Deko“, „jemand, der schlecht tanzt“. Jeder Gast zieht beim Ankommen einen. Das bringt die verschiedenen Freundeskreise zusammen.' },
        { t: 'Ein Film zum 18., ein anderer zum 60.', s: 'Das Prinzip funktioniert in jedem Alter, man muss es nur anpassen. Zum 18. lassen Sie die Jugendlichen mit wenigen Aufnahmen spielen, daran erinnern sie sich lange. Zum 60. stehen Familienfotos im Mittelpunkt, und der QR-Code wandert von einer Generation zur nächsten.' },
        { t: 'Die Überraschungsparty ohne Verräter', s: 'Für eine Überraschungsparty legen Sie das Album vorher an und schicken den Link an die Gäste, mit der Bitte, ihn nicht weiterzugeben. Das erste Foto des Abends sollte das Gesicht des Geburtstagskinds beim Hereinkommen sein. Sagen Sie allen Bescheid, damit zehn Handys bereit sind.' },
        { t: 'Der Einweg-Look mit eingeblendetem Datum', s: 'Wählen Sie im Album den Film „Einweg“: warme Farben, Körnung und das Datum in der Ecke wie auf alten Urlaubsfotos. Zum Geburtstag wirkt das orangefarbene Datum sofort wie eine Erinnerung, und es bleibt in den heruntergeladenen Fotos erhalten.' },
        { t: 'Abzüge statt Gästebuch', s: 'Statt eines Gästebuchs mit hastigen drei Worten lassen Sie nach der Präsentation eine Auswahl drucken und bitten die Gäste beim nächsten Treffen, etwas auf die Rückseite zu schreiben. Die Abzüge bestellen Sie direkt aus dem Album.' },
      ],
      conseilsTitre: 'Unsere Tipps für ein gelungenes Geburtstagsalbum',
      conseils: [
        'Wie viele Aufnahmen pro Gast? Bei 20 bis 30 Gästen ergeben 8 bis 10 Fotos pro Person ein reichhaltiges Album, ohne dass es endlos wird: zwei- bis dreihundert Bilder. Ab 40 Gästen reichen 5 oder 6 Aufnahmen, dann bleibt das Album übersichtlich und jeder wählt seine Momente bewusst. Hat jemand vor der Torte schon alles verbraucht, können Sie seinen Film nachladen.',
        'Wann ist der beste Präsentationstermin? Bei einer Abendfeier ist der nächste Tag gegen Mittag ideal: Alle haben geschlafen, und das Album kommt genau dann, wenn man sich vom Vorabend erzählt. Bei einer Feier tagsüber (Mittagessen mit der Familie, Kaffee und Kuchen) planen Sie die Präsentation am selben Abend gegen 21 Uhr, wenn alle zu Hause sind.',
        'Welches Paket? Zu einem Geburtstag kommen meist 15 bis 60 Personen. Bis 30 Gäste reicht das Paket für 4,99 €, bis 50 Gäste sind es 14,99 €, und für ein großes Fest kostet das Paket für 100 Gäste 29,99 €. Sie zahlen einmal, ohne Abo. Mit 5 Personen können Sie es vorher kostenlos testen, ohne Kreditkarte.',
      ],
      faq: [
        { q: 'Müssen meine Gäste eine App herunterladen?', a: 'Nein. Sie scannen den QR-Code mit der Handykamera, und die Kamera von Time to Flash öffnet sich im Browser. Keine App, kein Konto, nur ein Vorname. Für alle, die es mögen, gibt es eine iPhone-App, sie ist aber freiwillig.' },
        { q: 'Was kostet eine Einwegkamera zum Geburtstag mit Time to Flash?', a: 'Bis 5 Personen ist es kostenlos. Danach zahlen Sie einmalig je nach Gästezahl: 1,99 € für 10, 4,99 € für 30, 14,99 € für 50, 29,99 € für 100. Kein Abo, und der Download des Albums ist inklusive.' },
        { q: 'Klappt das auch mit Kindern und älteren Gästen?', a: 'Ja, genau dafür ist es gemacht: einmal scannen, ein Knopf zum Auslösen, sonst gibt es nichts zu verstehen. Großeltern lassen sich beim Scannen vielleicht kurz helfen, danach geht es von allein. Kinder lieben das Einweg-Prinzip, und die begrenzten Aufnahmen ersparen Ihnen hundert Fotos vom Hund.' },
        { q: 'Und wenn ein Gast kein Handy oder keinen Empfang hat?', a: 'Wer kein Handy hat, leiht sich eines und fotografiert unter dem eigenen Namen. Bricht das Netz ab, bleibt das Foto auf dem Handy und wird automatisch verschickt, sobald die Verbindung zurück ist. In Räumen mit schlechtem Empfang hängen Sie das WLAN-Passwort neben den QR-Code.' },
        { q: 'Geht das auch bei einer Überraschungsparty?', a: 'Ja. Legen Sie das Event vorher an, schicken Sie den Link an die Gäste, ohne dass das Geburtstagskind es sieht, und stellen Sie das Plakat erst im letzten Moment auf. Sie können einen Mitorganisator hinzufügen und vor der Präsentation ein Foto ausblenden, das zu viel verraten würde.' },
      ],
      ctaTitre: 'Holen Sie sich die Fotos der ganzen Feier',
      ctaSous: 'Richten Sie Ihre Einwegkamera zum Geburtstag in zwei Minuten ein. Bis 5 Gäste kostenlos.',
    },
  },
  'anniversaire-30-ans': {
    fr: {
      titre: 'Idée animation anniversaire 30 ans : le jetable partagé',
      description: 'Une idée d’animation pour un anniversaire de 30 ans : l’appareil photo jetable des années 2000 sur le téléphone de vos amis, révélé le lendemain.',
      eyebrow: 'Anniversaire 30 ans · idée d’animation',
      h1: 'Une idée d’animation pour vos 30 ans : le retour du jetable',
      intro: [
        'À 30 ans, on a connu les deux mondes. Les appareils jetables des colonies de vacances, les photos qu’on attendait une semaine chez le photographe, et aujourd’hui des milliers d’images qu’on ne regarde plus. Pour une fête de 30 ans, la nostalgie est déjà là : autant en faire une animation.',
        'Time to Flash ressort l’appareil jetable, mais sur le téléphone de vos amis. Ils scannent un QR code, l’appareil s’ouvre sans application, et chacun a quelques clichés pour toute la soirée. Aucune photo n’est visible avant le lendemain : on la découvre au réveil, tous ensemble, comme quand on récupérait les tirages.',
      ],
      ticks: ['L’esprit des jetables des années 2000', 'Sans application, un simple scan', 'Révélation au réveil'],
      pourquoiTitre: 'Pourquoi ça marche si bien pour des 30 ans',
      pourquoiSous: 'Une génération qui a grandi avec l’argentique et vit avec le smartphone : c’est exactement son terrain.',
      pourquoi: [
        { ic: '📼', t: 'La nostalgie fait le travail', s: 'Le jetable, c’est l’objet des voyages scolaires et des étés à 15 ans. Le ressortir pour vos 30 ans fait sourire tout le monde avant même la première photo.' },
        { ic: '🌙', t: 'Les photos de 3 h du matin, mais pas sur les réseaux', s: 'Une fête de 30 ans finit tard, et c’est là que naissent les meilleures photos. Elles restent dans un album privé, entre vous, au lieu de finir en story le soir même.' },
        { ic: '🏡', t: 'Parfait pour la maison louée', s: 'Gîte, maison de campagne, bar privatisé : le QR code se pose n’importe où. Et si la fête dure le week-end, l’appareil reste ouvert du vendredi au dimanche.' },
      ],
      etapes: [
        { t: 'L’affiche sur le frigo ou au comptoir', s: 'Dans une maison louée, collez l’affiche sur le frigo ou près des bières : c’est là que tout le monde revient. Dans un bar, posez-la sur le comptoir et à côté de la piste.' },
        { t: '10 clichés, comme une vraie pellicule', s: 'Donnez entre 8 et 12 clichés par personne : assez pour la soirée, assez peu pour qu’on hésite avant d’appuyer. On ne peut pas revoir ses photos, et c’est tout le charme.' },
        { t: 'La révélation au brunch du lendemain', s: 'Programmez la révélation pour le brunch ou le déjeuner du lendemain. Dans une maison louée, tout le monde la découvre autour de la table, les yeux encore fatigués.' },
      ],
      ideesTitre: 'Idées d’animation pour un anniversaire de 30 ans',
      ideesSous: 'Pas besoin d’un animateur ni d’un programme chargé : quelques idées bien choisies suffisent à faire une soirée dont on parle encore.',
      idees: [
        { t: 'La soirée à thème années 90 ou 2000', s: 'Demandez à chacun de venir habillé comme à 15 ans : survêtement à pression, jean taille basse, casquette, gloss à paillettes. La playlist suit, et les photos prises au jetable, avec la date incrustée, ont l’air de sortir d’une vraie boîte à chaussures.' },
        { t: 'Le « avant / maintenant »', s: 'Demandez aux invités d’apporter une photo d’eux avec vous il y a quinze ou vingt ans. Pendant la soirée, ils refont la même pose avec le même ami. L’album mélange alors les deux époques, et c’est souvent la série dont tout le monde parle.' },
        { t: 'Le quiz « qui le connaît le mieux »', s: 'Préparez vingt questions sur la personne fêtée : son premier concert, son pire job d’été, son surnom au lycée. Les équipes se forment au hasard, ce qui mélange les amis d’école, les collègues et le conjoint. Le perdant offre une tournée.' },
        { t: 'La pellicule de l’heure tardive', s: 'Lancez un défi : chacun garde ses deux derniers clichés pour après 1 h du matin. Ce sont ces photos-là qui manquent toujours, parce qu’à cette heure personne ne pense à sortir son téléphone. Là, il reste des clichés à utiliser, donc on y pense.' },
        { t: 'Le karaoké sans pitié', s: 'Un micro, un écran et une playlist de tubes de votre adolescence. Le karaoké donne les photos les plus expressives de la soirée : les yeux fermés sur le refrain, les bras levés, le public qui hurle. Placez un QR code à côté de l’écran.' },
        { t: 'Les lettres à ouvrir à 40 ans', s: 'Proposez aux invités d’écrire un mot à la personne fêtée, à ouvrir dans dix ans. Glissez dans l’enveloppe un tirage papier choisi dans l’album après la révélation. Dans dix ans, vous aurez la lettre et la photo de ce soir-là.' },
        { t: 'Le jeu des clichés cachés', s: 'Avant la soirée, choisissez cinq invités qui ont une mission secrète : photographier un détail précis (une chaussette dépareillée, le toast le plus long, la personne fêtée en train de bâiller). Le lendemain, au moment de la révélation, on essaie de deviner qui avait quelle mission.' },
      ],
      conseilsTitre: 'Nos conseils pour la soirée de vos 30 ans',
      conseils: [
        'Combien de clichés donner ? Une fête de 30 ans entre amis réunit souvent 20 à 40 personnes. À ce nombre, 10 clichés par invité donnent un album qui couvre toute la soirée, de l’apéro aux dernières danses. Si la fête dure tout le week-end dans une maison louée, montez à 12 ou 15 : il y a plus de moments à garder, et les rappels envoyés aux participants pendant le week-end relancent ceux qui oublient.',
        'À quelle heure révéler ? Pas trop tôt : une soirée de 30 ans finit rarement avant 3 h. Une révélation vers 12 h ou 13 h le lendemain tombe pile au moment du café ou du brunch. Pour un week-end entier, révélez le dimanche soir, une fois tout le monde rentré : c’est une jolie façon de prolonger la fête.',
        'Quelle formule choisir ? Pour 30 personnes ou moins, la formule à 4,99 € suffit. Si vous êtes entre 31 et 50, prenez celle à 14,99 €. C’est un paiement unique, sans abonnement, et le téléchargement de toutes les photos est compris. Vous pouvez tester l’appareil gratuitement à 5, sans carte bancaire, quelques jours avant.',
      ],
      faq: [
        { q: 'Faut-il installer une application pour participer ?', a: 'Non. Vos amis scannent le QR code et l’appareil photo s’ouvre dans leur navigateur. Pas de compte, pas de téléchargement, juste un prénom. C’est important à 2 h du matin, quand plus personne n’a envie de chercher un mot de passe.' },
        { q: 'Combien ça coûte pour une fête de 30 ans ?', a: 'La plupart des fêtes de 30 ans tiennent dans la formule 30 personnes (4,99 €) ou 50 personnes (14,99 €). C’est un paiement unique. Jusqu’à 5 participants, c’est gratuit.' },
        { q: 'Les photos de la soirée vont-elles finir sur les réseaux sociaux ?', a: 'Non, l’album est privé : seuls les participants y ont accès. Personne ne voit les photos pendant la soirée, donc personne ne les publie à chaud. Et avant la révélation, vous pouvez masquer une photo que vous préférez garder pour vous.' },
        { q: 'Et si la maison louée n’a pas de réseau ?', a: 'C’est fréquent à la campagne. Une photo prise sans réseau reste dans le téléphone et part toute seule dès que la connexion revient. Pour que l’appareil s’ouvre la première fois, affichez le code wifi de la maison juste à côté du QR code.' },
        { q: 'Peut-on organiser une surprise pour ses 30 ans ?', a: 'Oui. Un ami crée l’événement, envoie le lien aux invités, et peut vous ajouter plus tard comme co-organisateur. Le premier cliché de la soirée sera votre tête quand vous découvrirez tout le monde.' },
      ],
      ctaTitre: 'Ressortez le jetable pour vos 30 ans',
      ctaSous: 'Créez l’appareil photo de la soirée en deux minutes. Gratuit jusqu’à 5 personnes.',
    },
    en: {
      titre: '30th birthday party ideas: a shared disposable camera',
      description: 'One of the best 30th birthday party ideas: a 2000s-style disposable camera on all your friends’ phones, with the photos revealed the next morning.',
      eyebrow: '30th birthday · party ideas',
      h1: '30th birthday party ideas: bring back the disposable camera',
      intro: [
        'At 30, you have lived in both worlds. Disposable cameras on school trips, a week’s wait for prints at the chemist, and now thousands of photos nobody ever looks at. For a 30th, the nostalgia is already in the room, so you might as well turn it into the entertainment.',
        'Time to Flash brings back the disposable camera, on your friends’ phones. They scan a QR code, the camera opens with no app, and everyone gets a few shots for the whole night. Nothing can be seen until the next day: you all see them together when you wake up, just like picking up your prints.',
      ],
      ticks: ['That 2000s disposable feeling', 'No app, just a scan', 'Revealed when you wake up'],
      pourquoiTitre: 'Why it works so well for a 30th',
      pourquoiSous: 'A generation that grew up with film and lives on smartphones: this is home ground.',
      pourquoi: [
        { ic: '📼', t: 'Nostalgia does the work', s: 'The disposable is the camera of school trips and summers at 15. Bringing it back for your 30th gets a smile before anyone takes a single photo.' },
        { ic: '🌙', t: 'The 3am photos, kept off social media', s: 'A 30th tends to go on late, and that is when the best photos happen. They stay in a private album, between you, instead of turning up in someone’s story that night.' },
        { ic: '🏡', t: 'Perfect for a rented house', s: 'Holiday cottage, country house, a bar booked for the night: the QR code goes anywhere. If the party lasts all weekend, the camera stays open from Friday to Sunday.' },
      ],
      etapes: [
        { t: 'Poster on the fridge or the bar', s: 'In a rented house, stick the poster on the fridge or next to the beers: that is where everyone keeps coming back. In a bar, put one on the counter and one by the dance floor.' },
        { t: '10 shots, like a real roll of film', s: 'Give each person 8 to 12 shots: enough for the night, few enough that people think before pressing. Nobody can look back at their photos, and that is the whole charm.' },
        { t: 'The reveal over next day’s brunch', s: 'Schedule the reveal for brunch or lunch the next day. In a rented house, everyone discovers it around the table, still a bit bleary-eyed.' },
      ],
      ideesTitre: '30th birthday party ideas',
      ideesSous: 'No need for an entertainer or a packed schedule: a few well-chosen ideas are enough for a party people talk about for years.',
      idees: [
        { t: 'A 90s or 2000s theme', s: 'Ask everyone to come dressed the way they did at 15: popper tracksuits, low-rise jeans, bucket hats, glitter lip gloss. The playlist follows, and the photos on the disposable film, with the date stamp, look like they came straight out of a shoebox.' },
        { t: 'Then and now', s: 'Ask guests to bring a photo of themselves with you from fifteen or twenty years ago. During the party, they recreate the same pose with the same friend. The album ends up mixing both eras, and that set is usually the one everyone talks about.' },
        { t: 'The “who knows them best” quiz', s: 'Prepare twenty questions about the birthday person: first gig, worst summer job, nickname at school. Teams are drawn at random, which mixes school friends, colleagues and partners. The losing team buys a round.' },
        { t: 'The late-night roll', s: 'Set a challenge: everyone saves their last two shots for after 1am. Those are the photos that are always missing, because at that hour nobody thinks of getting their phone out. Here, there are shots left to use, so people remember.' },
        { t: 'Merciless karaoke', s: 'A mic, a screen and a playlist of the hits from your teenage years. Karaoke gives you the most expressive photos of the night: eyes shut on the chorus, arms in the air, the crowd yelling along. Put a QR code next to the screen.' },
        { t: 'Letters to open at 40', s: 'Invite guests to write a note to the birthday person, to be opened in ten years. After the reveal, slip a print chosen from the album into each envelope. In ten years you will have the letter and a photo from that very night.' },
        { t: 'Secret photo missions', s: 'Before the party, give five guests a secret mission: photograph something specific (an odd sock, the longest toast, the birthday person yawning). The next day, during the reveal, everyone tries to guess who had which mission.' },
      ],
      conseilsTitre: 'Our tips for your 30th',
      conseils: [
        'How many shots to give? A 30th with friends usually brings together 20 to 40 people. At that size, 10 shots each gives an album that covers the whole night, from first drinks to last dance. If the party lasts a whole weekend in a rented house, go up to 12 or 15: there are more moments to keep, and the reminders sent to guests over the weekend nudge anyone who forgets.',
        'When to reveal? Not too early: a 30th rarely finishes before 3am. A reveal around 12 or 1pm the next day lands right at coffee or brunch time. For a full weekend, reveal on Sunday evening once everyone is home: a nice way to stretch the party out a little longer.',
        'Which plan to choose? For 30 people or fewer, the €4.99 plan is enough. Between 31 and 50, go for the €14.99 one. It is a one-off payment with no subscription, and downloading all the photos is included. You can try the camera for free with 5 people, no card needed, a few days before.',
      ],
      faq: [
        { q: 'Do guests need to install an app?', a: 'No. Your friends scan the QR code and the camera opens in their browser. No account, no download, just a first name. That matters at 2am, when nobody fancies hunting for a password.' },
        { q: 'How much does it cost for a 30th?', a: 'Most 30th parties fit in the 30-guest plan (€4.99) or the 50-guest plan (€14.99). It is a one-off payment. Up to 5 people, it is free.' },
        { q: 'Will the party photos end up on social media?', a: 'No, the album is private: only the guests can see it. Nobody sees the photos during the party, so nobody posts them in the heat of the moment. Before the reveal, you can also hide any photo you would rather keep to yourself.' },
        { q: 'What if the rented house has no signal?', a: 'That happens a lot in the countryside. A photo taken without signal stays on the phone and sends itself as soon as the connection is back. To make sure the camera opens the first time, put the house Wi-Fi password right next to the QR code.' },
        { q: 'Can a 30th be a surprise?', a: 'Yes. A friend creates the event, sends the link to the guests, and can add you as a co-organiser later. The first shot of the night will be your face as you walk in and see everyone.' },
      ],
      ctaTitre: 'Bring back the disposable for your 30th',
      ctaSous: 'Set up the party camera in two minutes. Free for up to 5 people.',
    },
    de: {
      titre: 'Ideen zum 30. Geburtstag: die gemeinsame digitale Einwegkamera',
      description: 'Eine der schönsten Ideen zum 30. Geburtstag: die Einwegkamera der 2000er auf dem Handy Ihrer Freunde, mit Präsentation der Fotos am nächsten Morgen.',
      eyebrow: '30. Geburtstag · Ideen',
      h1: 'Ideen zum 30. Geburtstag: die Rückkehr der Einwegkamera, jetzt digital',
      intro: [
        'Mit 30 kennt man beide Welten. Einwegkameras auf Klassenfahrt, eine Woche warten auf die Abzüge aus der Drogerie, und heute tausende Fotos, die keiner mehr anschaut. Bei einer Feier zum 30. ist die Nostalgie sowieso schon im Raum, also machen Sie doch ein Spiel daraus.',
        'Time to Flash holt die Einwegkamera zurück, auf die Handys Ihrer Freunde. Sie scannen einen QR-Code, die Kamera öffnet sich ohne App, und jeder hat ein paar Aufnahmen für den ganzen Abend. Vor dem nächsten Tag ist nichts zu sehen: Alle entdecken die Bilder gemeinsam nach dem Aufwachen, wie früher beim Abholen der Abzüge.',
      ],
      ticks: ['Einweg-Gefühl wie in den 2000ern', 'Ohne App, einfach scannen', 'Präsentation nach dem Aufwachen'],
      pourquoiTitre: 'Warum das zum 30. so gut passt',
      pourquoiSous: 'Eine Generation, die mit Film aufgewachsen ist und mit dem Smartphone lebt: genau ihr Terrain.',
      pourquoi: [
        { ic: '📼', t: 'Die Nostalgie erledigt den Rest', s: 'Die Einwegkamera gehört zu Klassenfahrten und Sommern mit 15. Holt man sie zum 30. wieder hervor, lächeln alle schon vor dem ersten Foto.' },
        { ic: '🌙', t: 'Die Fotos von 3 Uhr nachts, aber nicht auf Instagram', s: 'Ein 30. Geburtstag geht lange, und genau dann entstehen die besten Bilder. Sie bleiben in einem privaten Album unter Ihnen, statt noch in der Nacht in einer Story zu landen.' },
        { ic: '🏡', t: 'Ideal fürs gemietete Ferienhaus', s: 'Ferienhaus, Hütte, gemietete Bar: Der QR-Code passt überall hin. Dauert die Feier das ganze Wochenende, bleibt die Kamera von Freitag bis Sonntag offen.' },
      ],
      etapes: [
        { t: 'Das Plakat an den Kühlschrank oder die Theke', s: 'Im Ferienhaus kleben Sie das Plakat an den Kühlschrank oder neben das Bier: Dort kommen alle immer wieder vorbei. In einer Bar stellen Sie eines auf die Theke und eines neben die Tanzfläche.' },
        { t: '10 Aufnahmen wie auf einem echten Film', s: 'Geben Sie jedem 8 bis 12 Aufnahmen: genug für den Abend, wenig genug, dass man vor dem Auslösen überlegt. Die eigenen Fotos kann man nicht ansehen, und genau das ist der Reiz.' },
        { t: 'Die Präsentation beim Brunch am nächsten Tag', s: 'Planen Sie die Präsentation für den Brunch oder das Mittagessen am nächsten Tag. Im Ferienhaus entdecken alle das Album gemeinsam am Tisch, noch etwas verschlafen.' },
      ],
      ideesTitre: 'Ideen zum 30. Geburtstag',
      ideesSous: 'Sie brauchen weder Animateur noch volles Programm: Ein paar gut gewählte Ideen reichen für eine Feier, von der man noch lange spricht.',
      idees: [
        { t: 'Mottoparty 90er oder 2000er', s: 'Bitten Sie alle, so zu kommen wie mit 15: Trainingsanzug mit Druckknöpfen, Hüftjeans, Buffalo-Schuhe, Glitzer-Lipgloss. Die Playlist zieht mit, und die Fotos im Einweg-Look mit eingeblendetem Datum sehen aus wie aus einem echten Schuhkarton.' },
        { t: 'Damals und heute', s: 'Bitten Sie die Gäste, ein Foto von sich mit Ihnen von vor fünfzehn oder zwanzig Jahren mitzubringen. Auf der Feier stellen sie dieselbe Pose mit derselben Person nach. Das Album mischt dann beide Zeiten, und meist ist das die Serie, über die alle reden.' },
        { t: 'Das Quiz „Wer kennt das Geburtstagskind am besten?“', s: 'Bereiten Sie zwanzig Fragen vor: erstes Konzert, schlimmster Ferienjob, Spitzname in der Schule. Die Teams werden ausgelost, so mischen sich Schulfreunde, Kollegen und Partner. Das Verliererteam gibt eine Runde aus.' },
        { t: 'Der Film für späte Stunden', s: 'Eine kleine Challenge: Jeder hebt seine letzten zwei Aufnahmen für nach 1 Uhr auf. Genau diese Fotos fehlen sonst immer, weil um diese Zeit niemand mehr ans Handy denkt. Hier sind noch Aufnahmen übrig, also denkt man daran.' },
        { t: 'Karaoke ohne Gnade', s: 'Ein Mikro, ein Bildschirm und die Hits Ihrer Jugend. Karaoke liefert die ausdrucksstärksten Fotos des Abends: geschlossene Augen beim Refrain, Arme in der Luft, das Publikum grölt mit. Stellen Sie einen QR-Code neben den Bildschirm.' },
        { t: 'Briefe zum 40.', s: 'Laden Sie die Gäste ein, dem Geburtstagskind einen Brief zu schreiben, der erst in zehn Jahren geöffnet wird. Legen Sie nach der Präsentation einen Abzug aus dem Album in jeden Umschlag. In zehn Jahren haben Sie den Brief und ein Foto genau von diesem Abend.' },
        { t: 'Geheime Fotoaufträge', s: 'Geben Sie vor der Feier fünf Gästen einen geheimen Auftrag: etwas Bestimmtes fotografieren (eine einzelne Socke, die längste Rede, das gähnende Geburtstagskind). Bei der Präsentation am nächsten Tag rät man, wer welchen Auftrag hatte.' },
      ],
      conseilsTitre: 'Unsere Tipps für Ihren 30.',
      conseils: [
        'Wie viele Aufnahmen pro Gast? Zu einem 30. unter Freunden kommen meist 20 bis 40 Leute. Bei dieser Größe ergeben 10 Aufnahmen pro Person ein Album, das den ganzen Abend abdeckt, vom Sekt bis zum letzten Tanz. Dauert die Feier ein ganzes Wochenende im Ferienhaus, gehen Sie auf 12 bis 15: Es gibt mehr Momente, und die Erinnerungen, die während des Wochenendes an die Gäste gehen, holen alle zurück, die es vergessen.',
        'Wann ist der beste Präsentationstermin? Nicht zu früh: Ein 30. endet selten vor 3 Uhr. Eine Präsentation gegen 12 oder 13 Uhr am nächsten Tag passt genau zum Kaffee oder Brunch. Bei einem ganzen Wochenende planen Sie die Präsentation am Sonntagabend, wenn alle zu Hause sind: eine schöne Art, die Feier noch etwas zu verlängern.',
        'Welches Paket? Für bis zu 30 Personen reicht das Paket für 4,99 €. Zwischen 31 und 50 nehmen Sie das für 14,99 €. Sie zahlen einmal, ohne Abo, und der Download aller Fotos ist inklusive. Ein paar Tage vorher können Sie die Kamera mit 5 Personen kostenlos testen, ohne Kreditkarte.',
      ],
      faq: [
        { q: 'Müssen die Gäste eine App installieren?', a: 'Nein. Ihre Freunde scannen den QR-Code, und die Kamera öffnet sich im Browser. Kein Konto, kein Download, nur ein Vorname. Das zählt um 2 Uhr nachts, wenn niemand mehr ein Passwort suchen will.' },
        { q: 'Was kostet das für einen 30. Geburtstag?', a: 'Die meisten Feiern zum 30. passen in das Paket für 30 Gäste (4,99 €) oder für 50 Gäste (14,99 €). Sie zahlen einmal. Bis 5 Personen ist es kostenlos.' },
        { q: 'Landen die Partyfotos in den sozialen Netzwerken?', a: 'Nein, das Album ist privat: Nur die Gäste haben Zugriff. Während der Feier sieht niemand die Fotos, also postet sie auch niemand spontan. Vor der Präsentation können Sie außerdem jedes Foto ausblenden, das Sie lieber für sich behalten.' },
        { q: 'Und wenn das Ferienhaus keinen Empfang hat?', a: 'Auf dem Land kommt das oft vor. Ein Foto ohne Netz bleibt auf dem Handy und wird automatisch verschickt, sobald die Verbindung zurück ist. Damit sich die Kamera beim ersten Mal öffnet, hängen Sie das WLAN-Passwort des Hauses direkt neben den QR-Code.' },
        { q: 'Kann der 30. eine Überraschung sein?', a: 'Ja. Ein Freund legt das Event an, schickt den Link an die Gäste und kann Sie später als Mitorganisator hinzufügen. Das erste Foto des Abends ist dann Ihr Gesicht, wenn Sie hereinkommen und alle sehen.' },
      ],
      ctaTitre: 'Holen Sie die Einwegkamera zum 30. zurück',
      ctaSous: 'Richten Sie die Kamera für die Feier in zwei Minuten ein. Bis 5 Personen kostenlos.',
    },
  },
  'anniversaire-40-ans': {
    fr: {
      titre: 'Animation anniversaire 40 ans : un jetable pour tous',
      description: 'Une animation pour un anniversaire de 40 ans qui réunit amis d’enfance, famille et enfants : un appareil photo jetable partagé, sans application.',
      eyebrow: 'Anniversaire 40 ans · animation photo',
      h1: 'Une animation pour vos 40 ans qui fait jouer tout le monde, des enfants aux amis d’enfance',
      intro: [
        'Une fête de 40 ans ne ressemble à aucune autre. Il y a les amis du lycée qu’on n’a pas vus depuis des années, les collègues, les parents, la belle-famille, et une bande d’enfants qui court entre les tables. Trouver une animation qui parle à tout ce monde à la fois, c’est tout le défi.',
        'Time to Flash propose une animation simple : un appareil photo jetable partagé sur le téléphone de chaque invité. On scanne un QR code, l’appareil s’ouvre sans application, et chacun a quelques clichés. Les enfants s’amusent, les grands-parents participent, et le lendemain vous recevez la fête vue par tous les âges.',
      ],
      ticks: ['Un jeu pour tous les âges', 'Un scan, aucune installation', 'Toute la fête dans un album'],
      pourquoiTitre: 'Pourquoi c’est la bonne animation pour des 40 ans',
      pourquoiSous: 'Des cercles qui ne se connaissent pas, trois générations, et l’envie de garder une trace de chacun.',
      pourquoi: [
        { ic: '🤝', t: 'Les cercles se mélangent', s: 'Les amis d’enfance, les collègues et la famille ne se connaissent pas. Un jeu photo commun donne une raison de se parler, de se prendre en photo, de rire ensemble.' },
        { ic: '🧒', t: 'Les enfants deviennent photographes', s: 'Les enfants adorent avoir un appareil « pour de vrai » avec des photos comptées. Ils photographient ce que les adultes ne voient pas, à hauteur de table, et ce sont souvent les images les plus drôles.' },
        { ic: '👵', t: 'Trois générations dans le même album', s: 'Vos parents, vos amis, vos enfants : chacun voit la fête à sa façon. L’album rassemble tous ces regards, et vous gardez enfin une photo de chaque personne venue.' },
      ],
      etapes: [
        { t: 'Une affiche sur chaque table', s: 'Pour une fête assise avec des familles, posez une petite affiche au centre de chaque table, plus une grande à l’entrée. Les parents scannent pendant l’apéritif, et les enfants n’ont plus qu’à demander le téléphone.' },
        { t: 'Des clichés à partager en famille', s: 'Choisissez 6 à 8 clichés par participant. Un parent peut prêter son téléphone à son enfant, ou chaque grand enfant peut avoir le sien. Une fois la pellicule finie, on a fini : ça évite les téléphones vissés aux mains toute la soirée.' },
        { t: 'La révélation le dimanche soir', s: 'Avec des enfants, la fête se termine plus tôt et le lendemain est chargé. Programmez la révélation pour le dimanche soir, vers 20 h : les enfants sont couchés, et vous regardez l’album tranquillement.' },
      ],
      ideesTitre: 'Idées d’animation pour un anniversaire de 40 ans',
      ideesSous: 'Des idées qui marchent avec un public mélangé : amis, famille, enfants, et quelques amis perdus de vue.',
      idees: [
        { t: 'Le jeu des 40 photos', s: 'Préparez une liste de 40 choses à photographier pendant la fête, une pour chaque année : « quelqu’un qui porte la même couleur que vous », « un enfant sur les épaules d’un adulte », « trois générations sur la même photo ». Affichez la liste près du QR code. Le lendemain, l’album permet de vérifier lesquelles ont été trouvées.' },
        { t: 'Les retrouvailles des amis d’enfance', s: 'Si des amis du collège ou du lycée sont là, réunissez-les pour une photo de classe recomposée, dans le même ordre que sur l’ancienne si vous l’avez. Mettez l’ancienne photo à côté sur une table. C’est un moment fort, et souvent un bon prétexte pour un discours.' },
        { t: 'La mission photo des enfants', s: 'Confiez aux enfants une mission officielle : être les reporters de la fête. Donnez-leur une liste simple (« le gâteau », « papi qui danse », « la personne avec le plus beau chapeau ») et un téléphone de parent. Ils se sentent importants, et vous obtenez des photos que personne d’autre n’aurait prises.' },
        { t: 'La chronologie de vos 40 ans', s: 'Exposez au mur une photo de vous pour chaque décennie : 0, 10, 20, 30 ans. Les invités qui apparaissent sur une ancienne photo posent devant avec vous. Les plus jeunes découvrent leurs parents à leur âge, et ça fait toujours son effet.' },
        { t: 'Le portrait de famille du siècle', s: 'Profitez que toute la famille est réunie pour faire une vraie photo de groupe : grands-parents, parents, enfants, cousins. Désignez un invité qui n’en fait pas partie pour la prendre, et demandez-lui d’en faire deux ou trois. C’est souvent la seule photo de ce genre depuis le dernier mariage.' },
        { t: 'Les vœux sur ardoise', s: 'Plutôt qu’un discours au micro, demandez à chaque invité d’écrire en une phrase ce qu’il vous souhaite pour vos 40 prochaines années, sur une ardoise. Il se fait photographier avec l’ardoise. Le lendemain, l’album devient un livre de vœux illustré.' },
        { t: 'La pellicule jetable pour le tirage', s: 'Après la révélation, passez l’album en rendu « Jetable », avec la date incrustée, et commandez quelques tirages papier. Offrez-en un à chaque famille présente, ou glissez-les dans les cartes de remerciement : c’est un souvenir que les enfants garderont.' },
      ],
      conseilsTitre: 'Nos conseils pour l’album de vos 40 ans',
      conseils: [
        'Combien de clichés donner ? Une fête de 40 ans compte souvent entre 30 et 60 personnes, enfants compris. Avec ce nombre, 6 à 8 clichés par participant suffisent largement : l’album fera trois à quatre cents photos, ce qui se regarde encore avec plaisir. Les enfants épuisent leur pellicule en vingt minutes ; gardez la possibilité de recharger, ou demandez-leur de partager le téléphone d’un parent.',
        'À quelle heure révéler ? Si la fête a lieu le samedi soir, révélez le dimanche vers 20 h : la journée de récupération est passée, les enfants sont couchés, et chacun ouvre l’album au calme. Pour un déjeuner du dimanche, révélez le soir même. Pensez aux invités venus de loin : la révélation leur fait un souvenir à regarder pendant le trajet du retour.',
        'Quelle formule choisir ? Comptez chaque personne qui prendra des photos, y compris les grands enfants avec leur propre téléphone. Jusqu’à 50 participants, la formule à 14,99 € convient à la plupart des fêtes de 40 ans ; pour une petite fête de 30 personnes, celle à 4,99 € suffit ; au-delà de 50, la formule 100 coûte 29,99 €. Paiement unique, sans abonnement, et vous pouvez tester gratuitement à 5.',
      ],
      faq: [
        { q: 'Faut-il une application pour participer ?', a: 'Non. Un scan du QR code ouvre l’appareil photo dans le navigateur du téléphone, sans compte et sans téléchargement. C’est ce qui permet aux parents comme aux grands-parents de participer en quelques secondes.' },
        { q: 'Combien coûte cette animation pour 40 ans ?', a: 'C’est un paiement unique selon le nombre de participants : 4,99 € jusqu’à 30, 14,99 € jusqu’à 50, 29,99 € jusqu’à 100. C’est gratuit jusqu’à 5 personnes, sans carte bancaire. Le téléchargement de l’album est compris.' },
        { q: 'Les enfants peuvent-ils participer ?', a: 'Oui, et ils adorent. Un enfant peut utiliser le téléphone d’un parent sous son propre prénom, ce qui permet de savoir qui a pris quoi. Le nombre de clichés limité évite les rafales, et avant la révélation, vous pouvez masquer une photo ratée ou gênante.' },
        { q: 'Et si un invité n’a pas de smartphone ou pas de réseau ?', a: 'Il peut emprunter le téléphone d’un proche et prendre ses photos sous son prénom. Si le réseau coupe dans la salle, la photo reste dans le téléphone et part dès que la connexion revient. Affichez aussi le code wifi de la salle à côté du QR code.' },
        { q: 'Mon conjoint peut-il l’organiser en surprise ?', a: 'Oui. Il crée l’événement en secret, envoie le lien aux invités, et peut ajouter un co-organisateur (un ami d’enfance, par exemple) pour l’aider. Vous découvrirez l’album en même temps que tout le monde.' },
      ],
      ctaTitre: 'Une animation pour vos 40 ans, prête en deux minutes',
      ctaSous: 'Créez l’appareil photo partagé de la fête. Gratuit jusqu’à 5 participants.',
    },
    en: {
      titre: '40th birthday party ideas for all ages',
      description: '40th birthday party ideas for a crowd of old friends, family and kids: a shared disposable camera on everyone’s phone, with no app to install.',
      eyebrow: '40th birthday · party ideas',
      h1: '40th birthday party ideas that get everyone playing, from the kids to your oldest friends',
      intro: [
        'A 40th is unlike any other party. There are school friends you have not seen in years, colleagues, parents, in-laws, and a pack of children racing between the tables. Finding something that works for all of them at once is the real challenge.',
        'Time to Flash offers a simple idea: a shared disposable camera on every guest’s phone. Scan a QR code, the camera opens without an app, and everyone gets a few shots. The children have fun, the grandparents join in, and the next day you get the party as seen by every generation.',
      ],
      ticks: ['A game for every age', 'One scan, nothing to install', 'The whole party in one album'],
      pourquoiTitre: 'Why it suits a 40th',
      pourquoiSous: 'Groups who do not know each other, three generations, and the wish to keep a memory of everyone.',
      pourquoi: [
        { ic: '🤝', t: 'Groups start mixing', s: 'Childhood friends, colleagues and family do not know each other. A shared photo game gives them a reason to talk, take each other’s picture and laugh together.' },
        { ic: '🧒', t: 'The kids become photographers', s: 'Children love having a “real” camera with a set number of shots. They photograph what adults miss, from table height, and those are often the funniest pictures.' },
        { ic: '👵', t: 'Three generations in one album', s: 'Your parents, your friends, your children: each sees the party their own way. The album brings all those views together, and at last you have a photo of everyone who came.' },
      ],
      etapes: [
        { t: 'A poster on every table', s: 'For a seated party with families, put a small poster in the middle of each table and a big one by the entrance. Parents scan during drinks, and children just have to ask for the phone.' },
        { t: 'Shots to share as a family', s: 'Choose 6 to 8 shots per guest. A parent can lend their phone to a child, or older children can have their own. Once the roll is used up, that is it: no phones glued to hands all night.' },
        { t: 'The reveal on Sunday evening', s: 'With children around, the party ends earlier and the next day is busy. Schedule the reveal for Sunday evening around 8pm: the kids are in bed, and you can enjoy the album in peace.' },
      ],
      ideesTitre: '40th birthday party ideas',
      ideesSous: 'Ideas that work with a mixed crowd: friends, family, children, and a few friends you had lost touch with.',
      idees: [
        { t: 'The 40 photos game', s: 'Make a list of 40 things to photograph during the party, one for each year: “someone wearing the same colour as you”, “a child on an adult’s shoulders”, “three generations in one shot”. Put the list next to the QR code. The next day, the album shows which ones were found.' },
        { t: 'The old school friends reunion', s: 'If friends from school are there, gather them for a recreated class photo, in the same order as the original if you have it. Put the old photo on a table nearby. It is a lovely moment, and often a good cue for a speech.' },
        { t: 'The kids’ photo mission', s: 'Give the children an official job: they are the party reporters. Hand them a simple list (“the cake”, “grandad dancing”, “the best hat”) and a parent’s phone. They feel important, and you get pictures nobody else would have taken.' },
        { t: 'Your 40 years on the wall', s: 'Put up a photo of yourself from each decade: aged 0, 10, 20, 30. Guests who appear in an old photo pose in front of it with you. The youngest discover their parents at their own age, which always goes down well.' },
        { t: 'The family portrait of the decade', s: 'Make the most of everyone being together for a proper group photo: grandparents, parents, children, cousins. Ask a guest from outside the family to take it, and to take two or three. It is often the only photo like it since the last wedding.' },
        { t: 'Wishes on a slate', s: 'Instead of speeches on the mic, ask each guest to write one sentence on a small chalkboard: what they wish you for the next 40 years. They get photographed holding it. The next day, the album turns into an illustrated book of wishes.' },
        { t: 'Disposable prints to give away', s: 'After the reveal, switch the album to the “Disposable” film with the date stamp and order a few prints. Give one to each family that came, or slip them into your thank-you cards: the children will keep them for years.' },
      ],
      conseilsTitre: 'Our tips for your 40th album',
      conseils: [
        'How many shots to give? A 40th often brings together 30 to 60 people, children included. At that size, 6 to 8 shots each is plenty: the album will have three or four hundred photos, which is still a pleasure to browse. Children use up their roll in twenty minutes, so keep the option to top it up, or ask them to share a parent’s phone.',
        'When to reveal? If the party is on Saturday night, reveal on Sunday around 8pm: the recovery day is over, the children are asleep, and everyone opens the album in peace. For a Sunday lunch, reveal the same evening. Think of guests who travelled far: the reveal gives them something to look at on the way home.',
        'Which plan to choose? Count everyone who will take photos, including older children with their own phones. Up to 50 guests, the €14.99 plan suits most 40th parties; for a smaller party of 30, the €4.99 one is enough; above 50, the 100 plan costs €29.99. One-off payment, no subscription, and you can try it free with 5 people.',
      ],
      faq: [
        { q: 'Do guests need an app?', a: 'No. Scanning the QR code opens the camera in the phone’s browser, with no account and no download. That is what lets parents and grandparents join in within seconds.' },
        { q: 'How much does it cost for a 40th?', a: 'It is a one-off payment based on the number of guests: €4.99 up to 30, €14.99 up to 50, €29.99 up to 100. It is free for up to 5 people, no card needed. Downloading the album is included.' },
        { q: 'Can children take part?', a: 'Yes, and they love it. A child can use a parent’s phone under their own name, so you know who took what. The limited shots stop endless bursts, and before the reveal you can hide any blurry or awkward photo.' },
        { q: 'What if a guest has no smartphone or no signal?', a: 'They can borrow a friend’s phone and take photos under their own name. If the signal drops in the venue, the photo stays on the phone and sends itself once the connection is back. Put the venue’s Wi-Fi password next to the QR code as well.' },
        { q: 'Can my partner organise it as a surprise?', a: 'Yes. They create the event in secret, send the link to guests, and can add a co-organiser (an old school friend, for instance) to help. You will discover the album at the same time as everyone else.' },
      ],
      ctaTitre: 'A 40th birthday idea, ready in two minutes',
      ctaSous: 'Create the party’s shared camera. Free for up to 5 guests.',
    },
    de: {
      titre: 'Ideen zum 40. Geburtstag: Fotospaß für alle Generationen',
      description: 'Ideen zum 40. Geburtstag mit alten Freunden, Familie und Kindern: eine gemeinsame Einwegkamera auf jedem Handy, ganz ohne App zum Installieren.',
      eyebrow: '40. Geburtstag · Ideen',
      h1: 'Ideen zum 40. Geburtstag, bei denen alle mitmachen, von den Kindern bis zu den ältesten Freunden',
      intro: [
        'Ein 40. Geburtstag ist anders als jede andere Feier. Da sind Schulfreunde, die man seit Jahren nicht gesehen hat, Kollegen, Eltern, Schwiegerfamilie und eine Horde Kinder, die zwischen den Tischen herumrennt. Etwas zu finden, das alle gleichzeitig anspricht, ist die eigentliche Herausforderung.',
        'Time to Flash bietet eine einfache Idee: eine gemeinsame Einwegkamera auf dem Handy jedes Gastes. QR-Code scannen, die Kamera öffnet sich ohne App, und jeder hat ein paar Aufnahmen. Die Kinder haben Spaß, die Großeltern machen mit, und am nächsten Tag bekommen Sie die Feier aus der Sicht aller Generationen.',
      ],
      ticks: ['Ein Spiel für jedes Alter', 'Einmal scannen, nichts installieren', 'Die ganze Feier in einem Album'],
      pourquoiTitre: 'Warum das zum 40. passt',
      pourquoiSous: 'Freundeskreise, die sich nicht kennen, drei Generationen und der Wunsch, von allen eine Erinnerung zu behalten.',
      pourquoi: [
        { ic: '🤝', t: 'Die Kreise mischen sich', s: 'Kindheitsfreunde, Kollegen und Familie kennen sich nicht. Ein gemeinsames Fotospiel gibt einen Grund, miteinander zu reden, sich gegenseitig zu fotografieren und zusammen zu lachen.' },
        { ic: '🧒', t: 'Die Kinder werden Fotografen', s: 'Kinder lieben eine „echte“ Kamera mit abgezählten Bildern. Sie fotografieren, was Erwachsene übersehen, auf Tischhöhe, und oft sind das die lustigsten Aufnahmen.' },
        { ic: '👵', t: 'Drei Generationen in einem Album', s: 'Ihre Eltern, Ihre Freunde, Ihre Kinder: Jeder sieht die Feier auf seine Art. Das Album vereint all diese Blicke, und Sie haben endlich ein Foto von jedem, der gekommen ist.' },
      ],
      etapes: [
        { t: 'Ein Plakat auf jeden Tisch', s: 'Bei einer Feier mit festen Plätzen und Familien stellen Sie ein kleines Plakat in die Mitte jedes Tisches und ein großes an den Eingang. Die Eltern scannen beim Sektempfang, und die Kinder müssen nur noch nach dem Handy fragen.' },
        { t: 'Aufnahmen für die ganze Familie', s: 'Wählen Sie 6 bis 8 Aufnahmen pro Teilnehmer. Ein Elternteil kann sein Handy dem Kind leihen, oder ältere Kinder nehmen ihr eigenes. Ist der Film voll, ist Schluss: kein Handy, das den ganzen Abend in der Hand klebt.' },
        { t: 'Die Präsentation am Sonntagabend', s: 'Mit Kindern endet die Feier früher, und der nächste Tag ist voll. Planen Sie die Präsentation für Sonntagabend gegen 20 Uhr: Die Kinder schlafen, und Sie sehen sich das Album in Ruhe an.' },
      ],
      ideesTitre: 'Ideen zum 40. Geburtstag',
      ideesSous: 'Ideen für ein gemischtes Publikum: Freunde, Familie, Kinder und ein paar Freunde, die man aus den Augen verloren hatte.',
      idees: [
        { t: 'Das Spiel der 40 Fotos', s: 'Erstellen Sie eine Liste mit 40 Motiven, eines für jedes Lebensjahr: „jemand in Ihrer Lieblingsfarbe“, „ein Kind auf den Schultern eines Erwachsenen“, „drei Generationen auf einem Bild“. Hängen Sie die Liste neben den QR-Code. Am nächsten Tag zeigt das Album, welche Motive gefunden wurden.' },
        { t: 'Das Wiedersehen mit den Schulfreunden', s: 'Sind Freunde aus der Schulzeit da, stellen Sie das alte Klassenfoto nach, wenn möglich in derselben Reihenfolge. Legen Sie das Original daneben auf einen Tisch. Ein starker Moment, und oft ein guter Anlass für eine kleine Rede.' },
        { t: 'Der Fotoauftrag für die Kinder', s: 'Geben Sie den Kindern einen offiziellen Auftrag: Sie sind die Reporter der Feier. Dazu eine einfache Liste („die Torte“, „Opa beim Tanzen“, „der schönste Hut“) und ein Handy von Mama oder Papa. Sie fühlen sich wichtig, und Sie bekommen Bilder, die sonst niemand gemacht hätte.' },
        { t: 'Ihre 40 Jahre an der Wand', s: 'Hängen Sie ein Foto von sich aus jedem Jahrzehnt auf: mit 0, 10, 20, 30. Gäste, die auf einem alten Bild zu sehen sind, posieren mit Ihnen davor. Die Jüngsten sehen ihre Eltern in ihrem eigenen Alter, und das kommt immer gut an.' },
        { t: 'Das große Familienfoto', s: 'Nutzen Sie die Gelegenheit, dass alle da sind, für ein echtes Gruppenbild: Großeltern, Eltern, Kinder, Cousins. Bitten Sie einen Gast außerhalb der Familie, es aufzunehmen, und zwar zwei- oder dreimal. Oft ist es das einzige Bild dieser Art seit der letzten Hochzeit.' },
        { t: 'Wünsche auf der Tafel', s: 'Statt Reden am Mikro schreibt jeder Gast einen Satz auf eine kleine Kreidetafel: was er Ihnen für die nächsten 40 Jahre wünscht. Dann lässt er sich damit fotografieren. Am nächsten Tag wird das Album zu einem bebilderten Wunschbuch.' },
        { t: 'Abzüge im Einweg-Look zum Verschenken', s: 'Stellen Sie das Album nach der Präsentation auf den Film „Einweg“ mit eingeblendetem Datum und bestellen Sie ein paar Abzüge. Schenken Sie jeder Familie einen oder legen Sie sie in die Dankeskarten: Die Kinder heben sie jahrelang auf.' },
      ],
      conseilsTitre: 'Unsere Tipps für das Album zum 40.',
      conseils: [
        'Wie viele Aufnahmen pro Gast? Zu einem 40. kommen oft 30 bis 60 Personen, Kinder mitgezählt. Bei dieser Größe reichen 6 bis 8 Aufnahmen pro Person völlig: Das Album hat dann drei- bis vierhundert Fotos und lässt sich noch gut anschauen. Kinder verbrauchen ihren Film in zwanzig Minuten; halten Sie das Nachladen bereit oder lassen Sie sie das Handy eines Elternteils teilen.',
        'Wann ist der beste Präsentationstermin? Ist die Feier am Samstagabend, planen Sie die Präsentation am Sonntag gegen 20 Uhr: Der Erholungstag ist vorbei, die Kinder schlafen, und alle öffnen das Album in Ruhe. Bei einem Mittagessen am Sonntag präsentieren Sie das Album am selben Abend. Denken Sie an Gäste mit langer Anreise: Die Präsentation gibt ihnen etwas zum Anschauen auf der Heimfahrt.',
        'Welches Paket? Zählen Sie alle, die fotografieren werden, auch ältere Kinder mit eigenem Handy. Bis 50 Teilnehmer passt das Paket für 14,99 € zu den meisten Feiern zum 40.; für eine kleinere Feier mit 30 Personen reicht das für 4,99 €; über 50 kostet das Paket für 100 Gäste 29,99 €. Einmalige Zahlung, kein Abo, und mit 5 Personen können Sie kostenlos testen.',
      ],
      faq: [
        { q: 'Braucht man eine App?', a: 'Nein. Der Scan des QR-Codes öffnet die Kamera im Browser des Handys, ohne Konto und ohne Download. So können Eltern und Großeltern in wenigen Sekunden mitmachen.' },
        { q: 'Was kostet das zum 40. Geburtstag?', a: 'Sie zahlen einmal, je nach Teilnehmerzahl: 4,99 € bis 30, 14,99 € bis 50, 29,99 € bis 100. Bis 5 Personen ist es kostenlos, ohne Kreditkarte. Der Download des Albums ist inklusive.' },
        { q: 'Können Kinder mitmachen?', a: 'Ja, und sie lieben es. Ein Kind kann das Handy eines Elternteils unter eigenem Namen nutzen, so wissen Sie, wer was fotografiert hat. Die begrenzten Aufnahmen verhindern Serienbilder, und vor der Präsentation können Sie jedes verwackelte oder peinliche Foto ausblenden.' },
        { q: 'Und wenn ein Gast kein Smartphone oder keinen Empfang hat?', a: 'Er leiht sich das Handy eines anderen und fotografiert unter seinem eigenen Namen. Fällt im Saal das Netz aus, bleibt das Foto auf dem Handy und wird verschickt, sobald die Verbindung zurück ist. Hängen Sie auch das WLAN-Passwort des Saals neben den QR-Code.' },
        { q: 'Kann mein Partner das als Überraschung organisieren?', a: 'Ja. Er legt das Event heimlich an, schickt den Link an die Gäste und kann einen Mitorganisator hinzufügen (zum Beispiel einen alten Schulfreund). Sie entdecken das Album gleichzeitig mit allen anderen.' },
      ],
      ctaTitre: 'Eine Idee zum 40., in zwei Minuten startklar',
      ctaSous: 'Erstellen Sie die gemeinsame Kamera für die Feier. Bis 5 Gäste kostenlos.',
    },
  },
  'anniversaire-50-ans': {
    fr: {
      titre: 'Animation anniversaire 50 ans : photos de famille',
      description: 'Animation pour un anniversaire de 50 ans en famille : un QR code, aucune application, et des grands-parents aux petits-enfants, tous photographient.',
      eyebrow: 'Anniversaire 50 ans · animation en famille',
      h1: 'Une animation pour ses 50 ans où toute la famille photographie, même papi',
      intro: [
        'Les 50 ans, c’est souvent une fête de famille au sens large : les parents qui ont maintenant plus de 75 ans, les frères et sœurs, les enfants devenus adultes, parfois les premiers petits-enfants. Et bien souvent, ce sont les enfants qui organisent tout, en secret.',
        'Time to Flash est une animation photo pensée pour ce genre de tablée. Pas d’application à télécharger, pas de compte à créer : on scanne un QR code et l’appareil photo s’ouvre. Chacun a quelques clichés, les photos restent cachées pendant la fête, et le lendemain toute la famille découvre l’album en même temps.',
      ],
      ticks: ['Rien à installer, même pour les aînés', 'Idéal pour une fête surprise', 'Un album pour toute la famille'],
      pourquoiTitre: 'Pourquoi c’est l’animation idéale pour des 50 ans',
      pourquoiSous: 'Quatre générations autour d’une table, des aînés peu à l’aise avec le téléphone, et des enfants qui veulent faire une belle surprise.',
      pourquoi: [
        { ic: '👴', t: 'Les aînés participent sans effort', s: 'Pas de magasin d’applications, pas de mot de passe : un scan et un bouton. Les grands-parents qui n’envoient jamais de photos peuvent cette fois en prendre, et ce sont souvent les plus belles.' },
        { ic: '🎉', t: 'Taillé pour une surprise organisée par les enfants', s: 'Les enfants créent l’événement à l’avance, s’échangent le lien entre eux, et posent l’affiche au dernier moment. La personne fêtée découvre la fête, puis l’album le lendemain.' },
        { ic: '📖', t: 'Un vrai album de famille', s: 'Toutes les photos de tout le monde, au même endroit, téléchargeables d’un coup. De quoi faire des tirages pour ceux qui préfèrent le papier.' },
      ],
      etapes: [
        { t: 'L’affiche sur les tables du repas', s: 'Pour un repas de famille, posez une affiche par table, à côté du menu ou du plan de table. Les petits-enfants peuvent aider les grands-parents à scanner pendant l’apéritif : c’est souvent le début de la complicité de la soirée.' },
        { t: 'Des clichés pour chaque génération', s: 'Choisissez 8 à 10 clichés par personne. Personne ne voit ses photos, si bien que les plus âgés ne se demandent pas si elles sont « réussies » : on appuie, et on verra demain.' },
        { t: 'La révélation le lendemain en fin de matinée', s: 'Programmez la révélation pour le lendemain vers 11 h. Les aînés sont réveillés tôt, les plus jeunes ont fini leur nuit, et la famille peut regarder l’album ensemble au téléphone ou autour d’un dernier café.' },
      ],
      ideesTitre: 'Idées d’animation pour un anniversaire de 50 ans',
      ideesSous: 'Des moments à photographier et des petites animations qui fonctionnent avec toute la famille, des plus jeunes aux plus âgés.',
      idees: [
        { t: 'La photo des quatre générations', s: 'Si la mère ou le père de la personne fêtée est présent, réunissez quatre générations sur une même photo : arrière-grand-parent, grand-parent, parent, enfant. Faites-la tôt dans la journée, avant la fatigue. C’est la photo qu’on encadre, et souvent celle qu’on regarde le plus longtemps.' },
        { t: 'L’entrée de la surprise', s: 'Pour une fête surprise, organisez l’arrivée : tout le monde dans la même pièce, téléphones prêts, et un enfant qui fait entrer la personne fêtée. Désignez à l’avance trois ou quatre invités placés à des angles différents. Le lendemain, vous aurez la scène sous toutes ses coutures, de la surprise aux larmes.' },
        { t: 'Le diaporama des 50 ans, en vrai', s: 'Rassemblez avant la fête des photos de chaque décennie et affichez-les sur un fil avec des pinces à linge. Pendant la fête, les invités photographient leurs souvenirs préférés et se font prendre devant. Les petits-enfants découvrent leurs grands-parents à 20 ans, et les questions fusent.' },
        { t: 'Le tour de table des souvenirs', s: 'Au dessert, chaque branche de la famille raconte un souvenir en une minute. Pendant que l’un parle, un autre de la même table prend la photo. L’album garde ainsi la trace de chaque prise de parole, sans que personne n’ait à filmer.' },
        { t: 'Les petits-enfants reporters', s: 'Confiez aux petits-enfants une liste de photos à prendre : « mamie qui rit », « les mains de papi », « le gâteau avant qu’on le coupe », « quelqu’un qui pleure de joie ». Ils prennent leur mission très au sérieux, et leurs photos sont pleines de tendresse.' },
        { t: 'La danse des générations', s: 'Lancez un morceau de chaque époque : un tube des années 70 pour les parents, un des années 80 pour la personne fêtée, un récent pour les enfants. Chaque génération doit faire danser l’autre. Les photos de la piste à ce moment-là sont les plus joyeuses de l’album.' },
        { t: 'L’album papier pour les aînés', s: 'Certains grands-parents ne regarderont jamais un album en ligne. Après la révélation, choisissez une trentaine de photos, passez-les en rendu « Jetable » pour la date incrustée, et commandez des tirages depuis l’album. Offrez-les dans une boîte : c’est souvent le cadeau qui touche le plus.' },
        { t: 'Le livre de recettes de famille', s: 'Demandez à chaque invité d’apporter une recette de famille écrite à la main, et photographiez chacun avec sa fiche. Après la fête, réunissez fiches et photos dans un petit livre. C’est un souvenir qui sert, et qui traverse les générations.' },
      ],
      conseilsTitre: 'Nos conseils pour l’album de ses 50 ans',
      conseils: [
        'Combien de clichés donner ? Pour une fête de famille de 30 à 50 personnes, 8 clichés par participant suffisent : les aînés n’en utiliseront souvent que la moitié, les plus jeunes tout. Si un enfant ou un ado a fini sa pellicule avant le gâteau, l’organisateur peut la recharger en un instant. Inutile d’en donner 15 : un album de famille se regarde mieux quand il n’est pas noyé.',
        'À quelle heure révéler ? Le lendemain en fin de matinée, vers 11 h, est un bon compromis entre les lève-tôt et ceux qui ont dansé tard. Si une partie de la famille reste dormir ou déjeune ensemble le lendemain, calez la révélation juste avant le repas : l’album devient le sujet de conversation de la table. Pour un week-end entier en famille, révélez le dernier soir.',
        'Quelle formule choisir ? Comptez les personnes qui ont un téléphone, pas celles qui sont à table : les jeunes enfants photographient souvent avec celui d’un parent. Pour 30 personnes ou moins, la formule à 4,99 € suffit ; jusqu’à 50, prenez celle à 14,99 € ; pour une grande fête de famille, la formule 100 coûte 29,99 €. Paiement unique, et vous pouvez faire un essai gratuit à 5 avant le grand jour.',
      ],
      faq: [
        { q: 'Mes grands-parents vont-ils devoir installer une application ?', a: 'Non, et c’est le principal avantage pour une fête de 50 ans. Il suffit de scanner le QR code avec l’appareil photo du téléphone : l’appareil Time to Flash s’ouvre dans le navigateur. Pas de compte, pas de mot de passe, juste un prénom à écrire.' },
        { q: 'Combien coûte cette animation pour 50 ans ?', a: 'C’est un paiement unique : 4,99 € jusqu’à 30 participants, 14,99 € jusqu’à 50, 29,99 € jusqu’à 100. Jusqu’à 5 personnes, c’est gratuit. Pas d’abonnement, et le téléchargement de toutes les photos est compris.' },
        { q: 'Et si un invité n’a pas de smartphone ?', a: 'Il peut prendre ses photos avec le téléphone d’un proche, sous son propre prénom : ses clichés lui restent attribués dans l’album. Pour les aînés qui ne veulent pas photographier du tout, prévoyez des tirages papier après la révélation, commandés directement depuis l’album.' },
        { q: 'La salle n’a pas de réseau, comment faire ?', a: 'Une photo prise sans réseau est gardée dans le téléphone et envoyée dès que la connexion revient, même le lendemain. Pour que l’appareil s’ouvre au moment du scan, demandez le code wifi de la salle et écrivez-le sur l’affiche, à côté du QR code.' },
        { q: 'Comment organiser une surprise pour les 50 ans de mon père ou de ma mère ?', a: 'Créez l’événement plusieurs jours avant, ajoutez un frère ou une sœur en co-organisateur, et envoyez le lien aux invités en leur demandant la discrétion. Posez les affiches juste avant l’arrivée. Avant la révélation, vous pourrez masquer une photo qui ne vous plaît pas.' },
      ],
      ctaTitre: 'Une animation pour ses 50 ans, que toute la famille comprend',
      ctaSous: 'Créez l’appareil photo de la fête en deux minutes. Gratuit jusqu’à 5 participants.',
    },
    en: {
      titre: '50th birthday party ideas for the whole family',
      description: '50th birthday party ideas for all the family: one QR code, no app to install, and everyone from grandparents to grandchildren takes the photos.',
      eyebrow: '50th birthday · family party ideas',
      h1: '50th birthday party ideas where the whole family takes photos, even grandad',
      intro: [
        'A 50th is often a family party in the widest sense: parents now well into their seventies, brothers and sisters, grown-up children, sometimes the first grandchildren. And very often it is the children who organise the whole thing, in secret.',
        'Time to Flash is a photo game made for exactly this kind of gathering. No app to download, no account to create: you scan a QR code and the camera opens. Everyone gets a few shots, the photos stay hidden during the party, and the next day the whole family discovers the album together.',
      ],
      ticks: ['Nothing to install, even for grandparents', 'Ideal for a surprise party', 'One album for the whole family'],
      pourquoiTitre: 'Why it suits a 50th so well',
      pourquoiSous: 'Four generations around a table, older relatives who are not keen on phones, and children planning a lovely surprise.',
      pourquoi: [
        { ic: '👴', t: 'Older guests join in easily', s: 'No app store, no password: one scan and one button. Grandparents who never send photos can take some this time, and they are often the best ones.' },
        { ic: '🎉', t: 'Made for a surprise planned by the kids', s: 'The children create the event in advance, share the link among themselves, and put the poster out at the last minute. The birthday person discovers the party, then the album the next day.' },
        { ic: '📖', t: 'A real family album', s: 'Everyone’s photos in one place, ready to download in one go. Plenty to choose from for prints, for those who prefer paper.' },
      ],
      etapes: [
        { t: 'A poster on each dinner table', s: 'For a family meal, put a poster on every table, next to the menu or table plan. Grandchildren can help grandparents scan during drinks: it is often how the evening’s fun begins.' },
        { t: 'Shots for every generation', s: 'Choose 8 to 10 shots per person. Nobody can see their photos, so older guests do not worry whether they came out well: just press, and see tomorrow.' },
        { t: 'The reveal the next morning', s: 'Schedule the reveal for around 11am the next day. Older relatives are up early, younger ones have caught up on sleep, and the family can look at the album together over one last coffee.' },
      ],
      ideesTitre: '50th birthday party ideas',
      ideesSous: 'Moments to capture and small activities that work for the whole family, from the youngest to the oldest.',
      idees: [
        { t: 'Four generations in one photo', s: 'If the birthday person’s mother or father is there, gather four generations in one shot: great-grandparent, grandparent, parent, child. Do it early in the day, before people get tired. It is the photo that ends up framed, and often the one people look at longest.' },
        { t: 'The surprise entrance', s: 'For a surprise party, stage the arrival: everyone in one room, phones ready, and one of the children bringing the birthday person in. Pick three or four guests in advance and place them at different angles. The next day you will have the whole scene, from the shock to the happy tears.' },
        { t: 'A real-life slideshow', s: 'Before the party, collect photos from each decade and hang them on a string with clothes pegs. During the party, guests photograph their favourite memories and pose in front of them. Grandchildren discover their grandparents at 20, and the questions come thick and fast.' },
        { t: 'Memories round the table', s: 'At dessert, each branch of the family shares a one-minute memory. While one person speaks, someone else at the same table takes the photo. The album keeps a record of every speech, without anyone having to film.' },
        { t: 'The grandchildren as reporters', s: 'Give the grandchildren a list of photos to take: “granny laughing”, “grandad’s hands”, “the cake before it’s cut”, “someone crying happy tears”. They take the job very seriously, and their photos are full of tenderness.' },
        { t: 'The generations dance-off', s: 'Play a song from each era: a 70s hit for the parents, an 80s one for the birthday person, something recent for the children. Each generation has to get the other dancing. The dance floor photos from that moment are the happiest in the album.' },
        { t: 'A paper album for older relatives', s: 'Some grandparents will never look at an online album. After the reveal, choose around thirty photos, switch them to the “Disposable” film for the date stamp, and order prints from the album. Give them in a box: it is often the gift that moves people most.' },
        { t: 'A family recipe book', s: 'Ask each guest to bring a handwritten family recipe, and photograph everyone holding theirs. After the party, put the cards and photos together in a small book. It is a keepsake that gets used, and passed down.' },
      ],
      conseilsTitre: 'Our tips for a 50th birthday album',
      conseils: [
        'How many shots to give? For a family party of 30 to 50 people, 8 shots each is enough: older guests often use only half, younger ones use them all. If a child or teenager runs out before the cake, the organiser can top up their roll in a moment. No need to give 15: a family album is nicer to browse when it is not overflowing.',
        'When to reveal? Around 11am the next day strikes a good balance between early risers and those who danced late. If part of the family stays over or has lunch together the next day, time the reveal just before the meal: the album becomes the talk of the table. For a whole family weekend, reveal on the last evening.',
        'Which plan to choose? Count people with a phone, not people at the table: young children usually use a parent’s phone. For 30 people or fewer, the €4.99 plan is enough; up to 50, go for €14.99; for a big family party, the 100 plan costs €29.99. One-off payment, and you can do a free trial with 5 people before the big day.',
      ],
      faq: [
        { q: 'Will my grandparents have to install an app?', a: 'No, and that is the main advantage for a 50th. They just scan the QR code with their phone’s camera and the Time to Flash camera opens in the browser. No account, no password, just a first name to type.' },
        { q: 'How much does it cost for a 50th?', a: 'It is a one-off payment: €4.99 for up to 30 guests, €14.99 up to 50, €29.99 up to 100. Up to 5 people, it is free. No subscription, and downloading all the photos is included.' },
        { q: 'What if a guest has no smartphone?', a: 'They can take photos on a relative’s phone under their own name, and the shots stay credited to them in the album. For older guests who would rather not take photos at all, plan some prints after the reveal, ordered straight from the album.' },
        { q: 'The venue has no signal: what can we do?', a: 'A photo taken without signal is kept on the phone and sent as soon as the connection is back, even the next day. To make sure the camera opens when people scan, ask for the venue’s Wi-Fi password and write it on the poster next to the QR code.' },
        { q: 'How do I plan a surprise 50th for my mum or dad?', a: 'Create the event a few days ahead, add a brother or sister as co-organiser, and send the link to guests asking them to keep it quiet. Put the posters out just before the arrival. Before the reveal, you can hide any photo you are not happy with.' },
      ],
      ctaTitre: 'A 50th birthday idea the whole family gets',
      ctaSous: 'Set up the party camera in two minutes. Free for up to 5 guests.',
    },
    de: {
      titre: 'Ideen zum 50. Geburtstag: Fotos mit der ganzen Familie',
      description: 'Ideen zum 50. Geburtstag mit der ganzen Familie: ein QR-Code, keine App, und von den Großeltern bis zu den Enkeln fotografieren alle mit.',
      eyebrow: '50. Geburtstag · Ideen für die Familienfeier',
      h1: 'Ideen zum 50. Geburtstag, bei denen die ganze Familie fotografiert, sogar Opa',
      intro: [
        'Ein 50. ist oft ein Familienfest im weitesten Sinn: die Eltern, inzwischen weit über 70, Geschwister, erwachsene Kinder, manchmal die ersten Enkel. Und sehr oft organisieren die Kinder alles, heimlich.',
        'Time to Flash ist ein Fotospiel, das genau für solche Runden gemacht ist. Keine App zum Herunterladen, kein Konto: QR-Code scannen, und die Kamera öffnet sich. Jeder hat ein paar Aufnahmen, die Fotos bleiben während der Feier verborgen, und am nächsten Tag entdeckt die ganze Familie das Album gemeinsam.',
      ],
      ticks: ['Nichts zu installieren, auch für Oma und Opa', 'Ideal für eine Überraschungsparty', 'Ein Album für die ganze Familie'],
      pourquoiTitre: 'Warum das zum 50. so gut passt',
      pourquoiSous: 'Vier Generationen an einem Tisch, ältere Gäste, die mit dem Handy fremdeln, und Kinder, die eine schöne Überraschung planen.',
      pourquoi: [
        { ic: '👴', t: 'Die Älteren machen mühelos mit', s: 'Kein App Store, kein Passwort: einmal scannen, ein Knopf. Großeltern, die sonst nie Fotos verschicken, machen diesmal selbst welche, und oft sind es die schönsten.' },
        { ic: '🎉', t: 'Wie gemacht für eine Überraschung der Kinder', s: 'Die Kinder legen das Event vorher an, teilen den Link untereinander und stellen das Plakat erst im letzten Moment auf. Das Geburtstagskind entdeckt erst die Feier, am nächsten Tag dann das Album.' },
        { ic: '📖', t: 'Ein echtes Familienalbum', s: 'Die Fotos aller an einem Ort, auf einen Schlag herunterzuladen. Genug Auswahl für Abzüge, für alle, die Papier lieber mögen.' },
      ],
      etapes: [
        { t: 'Das Plakat auf die Tische beim Essen', s: 'Bei einem Familienessen stellen Sie auf jeden Tisch ein Plakat, neben die Menükarte oder den Sitzplan. Die Enkel helfen den Großeltern beim Scannen während des Sektempfangs: oft der Anfang einer schönen Komplizenschaft für den Abend.' },
        { t: 'Aufnahmen für jede Generation', s: 'Wählen Sie 8 bis 10 Aufnahmen pro Person. Niemand sieht seine Fotos, also fragen sich die Älteren nicht, ob sie „gelungen“ sind: auslösen und morgen schauen.' },
        { t: 'Die Präsentation am nächsten Vormittag', s: 'Planen Sie die Präsentation für den nächsten Tag gegen 11 Uhr. Die Älteren sind früh wach, die Jüngeren haben ausgeschlafen, und die Familie kann das Album zusammen bei einem letzten Kaffee ansehen.' },
      ],
      ideesTitre: 'Ideen zum 50. Geburtstag',
      ideesSous: 'Momente zum Festhalten und kleine Programmpunkte, die mit der ganzen Familie funktionieren, von den Jüngsten bis zu den Ältesten.',
      idees: [
        { t: 'Vier Generationen auf einem Foto', s: 'Ist die Mutter oder der Vater des Geburtstagskinds dabei, bringen Sie vier Generationen auf ein Bild: Urgroßeltern, Großeltern, Eltern, Kind. Machen Sie es früh am Tag, bevor die Müdigkeit kommt. Dieses Foto wird eingerahmt, und oft ist es das, das man am längsten betrachtet.' },
        { t: 'Der Überraschungsmoment', s: 'Inszenieren Sie bei einer Überraschungsparty die Ankunft: alle in einem Raum, Handys bereit, und eines der Kinder führt das Geburtstagskind herein. Bestimmen Sie vorher drei oder vier Gäste an verschiedenen Plätzen. Am nächsten Tag haben Sie die Szene aus allen Blickwinkeln, vom Schreck bis zu den Freudentränen.' },
        { t: 'Die Diashow zum Anfassen', s: 'Sammeln Sie vor der Feier Fotos aus jedem Jahrzehnt und hängen Sie sie mit Wäscheklammern an eine Leine. Während der Feier fotografieren die Gäste ihre Lieblingserinnerungen und lassen sich davor ablichten. Die Enkel sehen ihre Großeltern mit 20, und die Fragen hören nicht auf.' },
        { t: 'Die Erinnerungsrunde am Tisch', s: 'Beim Dessert erzählt jeder Zweig der Familie eine Erinnerung in einer Minute. Während einer spricht, macht jemand am selben Tisch das Foto. So hält das Album jede Rede fest, ohne dass jemand filmen muss.' },
        { t: 'Die Enkel als Reporter', s: 'Geben Sie den Enkeln eine Liste mit Motiven: „Oma, die lacht“, „Opas Hände“, „die Torte vor dem Anschneiden“, „jemand, der vor Freude weint“. Sie nehmen den Auftrag sehr ernst, und ihre Fotos sind voller Zärtlichkeit.' },
        { t: 'Der Tanz der Generationen', s: 'Spielen Sie einen Song aus jeder Zeit: einen Hit aus den 70ern für die Eltern, einen aus den 80ern für das Geburtstagskind, einen aktuellen für die Kinder. Jede Generation muss die andere zum Tanzen bringen. Die Fotos von der Tanzfläche in diesem Moment sind die fröhlichsten im Album.' },
        { t: 'Ein Papieralbum für die Älteren', s: 'Manche Großeltern werden nie ein Online-Album ansehen. Wählen Sie nach der Präsentation etwa dreißig Fotos aus, stellen Sie sie auf den Film „Einweg“ mit eingeblendetem Datum und bestellen Sie Abzüge direkt aus dem Album. In einer Schachtel verschenkt, rührt das oft am meisten.' },
        { t: 'Das Familienrezeptbuch', s: 'Bitten Sie jeden Gast, ein handgeschriebenes Familienrezept mitzubringen, und fotografieren Sie alle mit ihrer Karte. Nach der Feier fassen Sie Karten und Fotos in einem kleinen Buch zusammen. Eine Erinnerung, die man benutzt und weitergibt.' },
      ],
      conseilsTitre: 'Unsere Tipps für das Album zum 50.',
      conseils: [
        'Wie viele Aufnahmen pro Gast? Bei einer Familienfeier mit 30 bis 50 Personen reichen 8 Aufnahmen pro Teilnehmer: Die Älteren nutzen oft nur die Hälfte, die Jüngeren alle. Hat ein Kind oder Teenager seinen Film schon vor der Torte verbraucht, kann der Organisator ihn sofort nachladen. 15 Aufnahmen sind unnötig: Ein Familienalbum schaut man lieber an, wenn es nicht überquillt.',
        'Wann ist der beste Präsentationstermin? Am nächsten Tag gegen 11 Uhr ist ein guter Kompromiss zwischen Frühaufstehern und denen, die lange getanzt haben. Übernachtet ein Teil der Familie oder isst am nächsten Tag gemeinsam, legen Sie die Präsentation kurz vor das Essen: Das Album wird zum Tischgespräch. Bei einem ganzen Familienwochenende präsentieren Sie das Album am letzten Abend.',
        'Welches Paket? Zählen Sie Personen mit Handy, nicht Personen am Tisch: Kleine Kinder fotografieren meist mit dem Handy eines Elternteils. Bis 30 Personen reicht das Paket für 4,99 €; bis 50 nehmen Sie das für 14,99 €; für ein großes Familienfest kostet das Paket für 100 Gäste 29,99 €. Einmalige Zahlung, und mit 5 Personen können Sie vor dem großen Tag kostenlos testen.',
      ],
      faq: [
        { q: 'Müssen meine Großeltern eine App installieren?', a: 'Nein, und das ist der größte Vorteil bei einem 50. Sie scannen den QR-Code einfach mit der Handykamera, und die Kamera von Time to Flash öffnet sich im Browser. Kein Konto, kein Passwort, nur ein Vorname.' },
        { q: 'Was kostet das zum 50. Geburtstag?', a: 'Sie zahlen einmal: 4,99 € bis 30 Teilnehmer, 14,99 € bis 50, 29,99 € bis 100. Bis 5 Personen ist es kostenlos. Kein Abo, und der Download aller Fotos ist inklusive.' },
        { q: 'Und wenn ein Gast kein Smartphone hat?', a: 'Er fotografiert mit dem Handy eines Angehörigen unter eigenem Namen, und seine Bilder bleiben ihm im Album zugeordnet. Für ältere Gäste, die gar nicht fotografieren möchten, planen Sie nach der Präsentation Abzüge ein, direkt aus dem Album bestellt.' },
        { q: 'Im Saal gibt es keinen Empfang: was tun?', a: 'Ein Foto ohne Netz wird auf dem Handy gespeichert und verschickt, sobald die Verbindung zurück ist, notfalls am nächsten Tag. Damit sich die Kamera beim Scannen öffnet, fragen Sie nach dem WLAN-Passwort des Saals und schreiben Sie es neben den QR-Code auf das Plakat.' },
        { q: 'Wie organisiere ich eine Überraschung zum 50. meiner Mutter oder meines Vaters?', a: 'Legen Sie das Event ein paar Tage vorher an, fügen Sie einen Bruder oder eine Schwester als Mitorganisator hinzu und schicken Sie den Link an die Gäste mit der Bitte um Verschwiegenheit. Stellen Sie die Plakate kurz vor der Ankunft auf. Vor der Präsentation können Sie jedes Foto ausblenden, das Ihnen nicht gefällt.' },
      ],
      ctaTitre: 'Eine Idee zum 50., die die ganze Familie versteht',
      ctaSous: 'Richten Sie die Kamera für die Feier in zwei Minuten ein. Bis 5 Teilnehmer kostenlos.',
    },
  },
}
