// Contenu de la page baptême (fr, en, de). Voir src/lib/occasions.js.
export const BAPTEME = {
  'bapteme': {
    fr: {
      titre: 'Animation baptême : les photos de tous vos invités',
      description: 'Une animation baptême simple : un QR code, l’appareil photo jetable sur le téléphone de chaque invité, et un album révélé pour l’enfant.',
      eyebrow: 'Baptême · animation photo',
      h1: 'Une animation photo pour le baptême, et un album que l’enfant gardera',
      intro: [
        'Un baptême, c’est souvent la seule journée où les arrière-grands-parents, les cousins éloignés, le parrain et la marraine se retrouvent autour du même enfant. Et pourtant, le soir, les parents n’ont presque aucune photo : ils ont passé la journée à porter le bébé, à le changer, à accueillir tout le monde. Les images existent, mais elles sont éparpillées dans les téléphones des invités.',
        'Time to Flash rassemble ces photos dans un seul album. Une affiche avec un QR code sur la table du repas, un scan, et l’appareil photo s’ouvre dans le navigateur, sans application ni compte. Chaque invité a quelques clichés, personne ne voit rien sur le moment, et toutes les photos sont révélées ensemble à l’heure que vous avez choisie. Religieux ou civil, le principe est le même.',
      ],
      ticks: ['Un simple scan, même pour les grands-parents', 'Gratuit jusqu’à 5 invités', 'Un album privé pour l’enfant'],
      pourquoiTitre: 'Pourquoi un appareil jetable partagé pour un baptême',
      pourquoiSous: 'Une fête de famille où les parents ont les bras pris et où chaque génération voit la journée à sa façon.',
      pourquoi: [
        { ic: '👶', t: 'Les parents ont enfin les photos', s: 'Avec un bébé dans les bras, on ne photographie pas. Grâce à l’album commun, les parents récupèrent ce que chaque invité a vu : les sourires, les siestes, les passages de bras en bras.' },
        { ic: '👵', t: 'Facile pour toutes les générations', s: 'Pas d’application à installer, pas de mot de passe. On scanne, on tape son prénom, on appuie sur un bouton. Les grands-parents s’y mettent vite, et les plus jeunes les aident volontiers.' },
        { ic: '📖', t: 'Un souvenir pour plus tard', s: 'Le jour de son baptême, l’enfant ne retiendra rien. L’album, lui, restera : téléchargé, imprimé ou transformé en livre photo, il lui racontera un jour qui était là.' },
      ],
      etapes: [
        { t: 'L’affiche sur le lieu du repas', s: 'Créez l’événement en deux minutes et imprimez l’affiche avec son QR code. Posez-la sur les tables du repas ou près du vin d’honneur, plutôt que dans le lieu de la cérémonie : on prend les photos après, dans la fête.' },
        { t: 'Quelques clichés par invité', s: 'Vous choisissez le nombre de photos par personne, de 3 à 15. Les photos partent dans l’album sans qu’on puisse les revoir, comme avec un vrai jetable. Chacun choisit ses moments avec soin.' },
        { t: 'La révélation le soir ou le lendemain', s: 'Programmez la révélation le soir même, une fois tout le monde rentré, ou le lendemain matin. Les invités reçoivent un lien et découvrent l’album en même temps que vous.' },
      ],
      ideesTitre: 'Idées d’animation photo pour un baptême',
      ideesSous: 'Des idées simples qui demandent peu de préparation et donnent à l’album une vraie valeur de souvenir de famille.',
      idees: [
        { t: 'Le portrait avec le parrain et la marraine', s: 'C’est la photo que tout le monde attend, et souvent celle qui manque. Confiez la mission à un invité précis dès le début du repas : le parrain, la marraine et l’enfant, de face, puis une deuxième plus spontanée. Avec plusieurs téléphones, vous aurez forcément une bonne image.' },
        { t: 'Les quatre générations', s: 'Quand l’arrière-grand-mère, la grand-mère, le parent et l’enfant sont réunis, c’est une photo qui ne se refait pas. Prévoyez un moment calme, une chaise pour la plus âgée, et laissez plusieurs invités la prendre sous des angles différents.' },
        { t: 'Chaque invité avec le bébé', s: 'Lancez la règle au dessert : chacun garde un cliché pour une photo avec l’enfant dans les bras ou sur les genoux. À la révélation, vous avez un portrait de l’enfant avec chaque personne présente. Pensez aux pauses : un bébé fatigué, ça se respecte.' },
        { t: 'Le livre d’or photo', s: 'Au lieu d’un livre d’or où l’on écrit vite une phrase, faites tirer les photos après la révélation et demandez aux proches d’écrire un mot au dos, à la prochaine visite. Les tirages papier se commandent directement depuis l’album, et le livre d’or se construit avec les images de la journée.' },
        { t: 'Le message pour ses 18 ans', s: 'Posez une petite carte à chaque place : « Un mot pour ses 18 ans ». Chaque invité l’écrit, puis la photographie avec son appareil, sous son prénom. Les cartes rejoignent une boîte que l’enfant ouvrira bien plus tard, et l’album en garde la trace.' },
        { t: 'La table des enfants', s: 'Les cousins et les petits amis de la famille ont souvent leur propre table. Laissez-leur un téléphone ou deux avec quelques clichés : ils photographient ce que les adultes ne voient pas, à leur hauteur. Ce sont souvent les images les plus drôles de l’album.' },
        { t: 'Le lâcher de bulles', s: 'À la sortie de la cérémonie ou au moment du gâteau, distribuez des flacons de bulles de savon. C’est joli, sans danger pour le bébé ni pour l’environnement, et c’est un moment parfait à prendre de tous les côtés à la fois.' },
        { t: 'Le rendu jetable avec la date', s: 'Dans l’album, essayez la pellicule « Jetable » : couleurs chaudes, grain, et la date incrustée dans le coin. Pour un baptême, cette date sur la photo prend tout son sens : c’est celle que l’enfant retrouvera dans ses albums, et elle reste dans les photos téléchargées.' },
      ],
      conseilsTitre: 'Nos conseils pour réussir l’album du baptême',
      conseils: [
        'Respecter le lieu de la cérémonie. Dans une église comme dans une salle de mairie, la cérémonie est un moment de recueillement, et l’officiant peut demander qu’on ne photographie pas. Annoncez simplement que l’appareil s’utilise après, et posez l’affiche uniquement sur le lieu du repas. Les invités arrivent alors avec tous leurs clichés pour la fête.',
        'Combien de clichés donner, et quand révéler ? Pour un baptême, 5 à 8 clichés par personne suffisent : la journée est plus calme qu’une soirée, et chaque photo compte davantage. Pour un déjeuner, révélez le soir même vers 20 h ; pour un repas qui s’étire jusqu’au soir, le lendemain matin. Si un grand-parent a tout utilisé trop vite, vous pouvez recharger sa pellicule.',
        'Quelle formule choisir ? Un baptême réunit en général entre 20 et 60 personnes. Jusqu’à 30 participants, la formule à 4,99 € suffit ; jusqu’à 50, comptez 14,99 € ; au-delà, la formule 100 coûte 29,99 €. C’est un paiement unique, sans abonnement. Vous pouvez aussi essayer gratuitement avec 5 personnes, sans carte bancaire.',
      ],
      faq: [
        { q: 'Les grands-parents vont-ils s’en sortir ?', a: 'Oui. Il suffit de scanner le QR code avec l’appareil photo du téléphone, de taper son prénom et d’appuyer sur un bouton. Aucune application à installer, aucun compte à créer. Si quelqu’un bloque sur le scan, un petit-enfant l’aide une fois, ensuite tout se fait seul.' },
        { q: 'Est-ce adapté à un baptême civil ?', a: 'Tout à fait. L’appareil ne dépend pas de la cérémonie : il sert pendant la fête qui suit, qu’il s’agisse d’un baptême religieux, d’un baptême civil (aussi appelé républicain) ou d’une simple fête de bienvenue pour le bébé.' },
        { q: 'Combien coûte une animation photo pour un baptême ?', a: 'C’est gratuit jusqu’à 5 participants. Ensuite, c’est un paiement unique selon le nombre d’invités : 4,99 € pour 30, 14,99 € pour 50, 29,99 € pour 100. Pas d’abonnement, et le téléchargement de toutes les photos est compris.' },
        { q: 'Les photos de notre enfant restent-elles privées ?', a: 'Oui. L’album n’est jamais public : seules les personnes qui ont le lien y ont accès. Il est hébergé en Europe et supprimé au bout de 6 mois, et vous êtes prévenu avant. Pensez à télécharger les photos d’ici là. Avant la révélation, vous pouvez aussi masquer une photo que vous ne souhaitez pas partager.' },
        { q: 'Peut-on faire un livre photo ou des tirages ensuite ?', a: 'Oui. Vous pouvez télécharger toutes les photos pour composer un livre photo, ou commander des tirages papier directement depuis l’album. C’est une jolie idée de cadeau pour le parrain, la marraine ou les grands-parents.' },
      ],
      ctaTitre: 'Gardez toute la journée pour votre enfant',
      ctaSous: 'Créez l’appareil photo du baptême en deux minutes. Gratuit jusqu’à 5 invités.',
    },
    en: {
      titre: 'Christening party ideas: every guest’s photos',
      description: 'A simple christening party idea: one QR code turns every guest’s phone into a disposable camera, with an album revealed for your child.',
      eyebrow: 'Christening · photo idea',
      h1: 'A christening party idea that leaves your child an album to keep',
      intro: [
        'A christening is often the one day when great-grandparents, distant cousins and the godparents all gather around the same child. And yet by evening the parents have hardly any photos: they spent the day holding the baby, changing the baby and greeting everyone. The pictures exist, but they are scattered across the guests’ phones.',
        'Time to Flash brings those photos together in one album. A poster with a QR code on the lunch table, one scan, and the camera opens in the browser, with no app and no account. Every guest gets a few shots, nobody sees anything at the time, and all the photos are revealed together at the time you choose. Religious or not, it works the same way.',
      ],
      ticks: ['One scan, easy for grandparents', 'Free for up to 5 guests', 'A private album for your child'],
      pourquoiTitre: 'Why a shared disposable camera suits a christening',
      pourquoiSous: 'A family day where the parents’ hands are full and every generation sees it differently.',
      pourquoi: [
        { ic: '👶', t: 'The parents finally get the photos', s: 'With a baby in your arms, you do not take pictures. With one shared album, the parents get everything their guests saw: the smiles, the naps, the baby passed from arm to arm.' },
        { ic: '👵', t: 'Easy for every generation', s: 'No app to install, no password. You scan, type your first name and press a button. Grandparents pick it up quickly, and the younger ones are happy to help.' },
        { ic: '📖', t: 'A keepsake for later', s: 'Your child will not remember their christening. The album will stay: downloaded, printed or made into a photo book, it will one day show them who was there.' },
      ],
      etapes: [
        { t: 'Put the poster where you eat', s: 'Create the event in two minutes and print the poster with its QR code. Put it on the lunch tables or by the drinks, rather than in the church or ceremony room: photos are for the celebration afterwards.' },
        { t: 'A few shots per guest', s: 'You choose how many photos each person gets, from 3 to 15. Photos go straight to the album and cannot be viewed again, just like a real disposable. Everyone picks their moments with care.' },
        { t: 'The reveal that evening or the next day', s: 'Schedule the reveal for that evening, once everyone is home, or the next morning. Guests get a link and discover the album at the same moment you do.' },
      ],
      ideesTitre: 'Christening photo ideas for your guests',
      ideesSous: 'Simple ideas that need little preparation and turn the album into a real family keepsake.',
      idees: [
        { t: 'The godparents’ portrait', s: 'It is the photo everyone expects, and often the one that goes missing. Give the job to one guest at the start of the meal: godmother, godfather and child, facing the camera, then a more relaxed one. With several phones on it, you are bound to get a good shot.' },
        { t: 'Four generations', s: 'When great-grandmother, grandmother, parent and child are together, it is a photo you cannot take again. Plan a quiet moment, a chair for the eldest, and let several guests take it from different angles.' },
        { t: 'Every guest with the baby', s: 'Announce the rule at dessert: everyone saves one shot for a photo holding the baby or with the baby on their lap. At the reveal, you have a portrait of your child with every person who came. Build in breaks: a tired baby comes first.' },
        { t: 'A photo guest book', s: 'Instead of a guest book with a hurried line in it, print the photos after the reveal and ask family to write a note on the back next time they visit. Prints can be ordered straight from the album, and the guest book grows out of the day’s pictures.' },
        { t: 'A message for their 18th', s: 'Leave a small card at each place: “A note for your 18th birthday”. Each guest writes it, then photographs it with their camera, under their own name. The cards go into a box your child will open much later, and the album keeps a copy.' },
        { t: 'The children’s table', s: 'Cousins and family friends’ children often have their own table. Give them a phone or two with a few shots: they capture what adults miss, from their own height. These are often the funniest pictures in the album.' },
        { t: 'A bubble send-off', s: 'As you leave the ceremony or when the cake comes out, hand round small bottles of bubbles. It looks lovely, it is safe for the baby and kind to the venue, and it is a perfect moment to photograph from every side at once.' },
        { t: 'The disposable look with the date', s: 'In the album, try the “Disposable” film: warm colours, grain and the date printed in the corner. For a christening, that date on the photo really means something: it is the one your child will find in their albums, and it stays in the downloaded photos.' },
      ],
      conseilsTitre: 'Our tips for a great christening album',
      conseils: [
        'Respect the ceremony. In a church or a civil naming ceremony, it is a moment of reflection, and the person leading it may ask for no photos. Simply let guests know the camera is for afterwards, and put the poster only where you eat. Guests then arrive with all their shots ready for the celebration.',
        'How many shots, and when to reveal? For a christening, 5 to 8 shots each is plenty: the day is calmer than an evening party, and every photo counts for more. After a lunch, reveal the same evening around 8pm; if the meal runs into the evening, the next morning. If a grandparent uses everything too fast, you can top up their film.',
        'Which plan to choose? A christening usually brings together 20 to 60 people. Up to 30 guests, the €4.99 plan is enough; up to 50, it is €14.99; above that, the 100 plan costs €29.99. It is a one-off payment, with no subscription. You can also try it free with 5 people, no card needed.',
      ],
      faq: [
        { q: 'Will the grandparents manage?', a: 'Yes. They just scan the QR code with their phone’s camera, type their first name and press a button. No app to install, no account to create. If someone gets stuck on the scan, a grandchild helps once, and the rest is easy.' },
        { q: 'Does it work for a naming ceremony?', a: 'Absolutely. The camera has nothing to do with the ceremony itself: it is used during the celebration afterwards, whether that follows a christening, a civil naming ceremony or a simple welcome party for the baby.' },
        { q: 'How much does it cost for a christening?', a: 'It is free for up to 5 people. After that it is a one-off payment based on the number of guests: €4.99 for 30, €14.99 for 50, €29.99 for 100. No subscription, and downloading every photo is included.' },
        { q: 'Do our child’s photos stay private?', a: 'Yes. The album is never public: only people with the link can see it. It is hosted in Europe and deleted after 6 months, and you are warned beforehand, so remember to download the photos before then. Before the reveal, you can also hide any photo you would rather not share.' },
        { q: 'Can we make a photo book or prints afterwards?', a: 'Yes. You can download every photo to make a photo book, or order prints straight from the album. It makes a lovely present for the godparents or grandparents.' },
      ],
      ctaTitre: 'Keep the whole day for your child',
      ctaSous: 'Set up your christening camera in two minutes. Free for up to 5 guests.',
    },
    de: {
      titre: 'Taufe Ideen für die Feier: die Fotos aller Gäste',
      description: 'Eine einfache Idee für die Tauffeier: ein QR-Code macht das Handy jedes Gastes zur Einwegkamera, mit einem Album für Ihr Kind.',
      eyebrow: 'Taufe · Fotoidee',
      h1: 'Eine Idee für die Tauffeier, die Ihrem Kind ein Album schenkt',
      intro: [
        'Eine Taufe ist oft der einzige Tag, an dem Urgroßeltern, entfernte Cousins und die Paten zusammen um dasselbe Kind stehen. Und trotzdem haben die Eltern am Abend kaum Fotos: Sie haben den ganzen Tag das Baby getragen, gewickelt und alle begrüßt. Die Bilder gibt es, aber sie sind über die Handys der Gäste verstreut.',
        'Time to Flash sammelt diese Fotos in einem einzigen Album. Ein Plakat mit QR-Code auf dem Tisch, einmal scannen, und die Kamera öffnet sich im Browser, ohne App und ohne Konto. Jeder Gast hat ein paar Aufnahmen, niemand sieht etwas im Moment selbst, und alle Fotos werden zu der Uhrzeit präsentiert, die Sie festlegen. Ob kirchlich oder nicht: Das Prinzip ist dasselbe.',
      ],
      ticks: ['Einmal scannen, auch für Großeltern', 'Bis 5 Gäste kostenlos', 'Ein privates Album für Ihr Kind'],
      pourquoiTitre: 'Warum eine gemeinsame Einwegkamera zur Taufe passt',
      pourquoiSous: 'Ein Familienfest, bei dem die Eltern die Hände voll haben und jede Generation den Tag anders sieht.',
      pourquoi: [
        { ic: '👶', t: 'Die Eltern bekommen endlich die Fotos', s: 'Mit einem Baby im Arm fotografiert man nicht. Mit einem gemeinsamen Album bekommen die Eltern alles, was die Gäste gesehen haben: das Lächeln, die Nickerchen, das Baby, das von Arm zu Arm wandert.' },
        { ic: '👵', t: 'Einfach für jede Generation', s: 'Keine App, kein Passwort. Scannen, Vornamen eingeben, auf den Auslöser drücken. Großeltern kommen schnell zurecht, und die Jüngeren helfen gern.' },
        { ic: '📖', t: 'Eine Erinnerung für später', s: 'An seine Taufe wird sich Ihr Kind nicht erinnern. Das Album bleibt: heruntergeladen, gedruckt oder als Fotobuch zeigt es ihm eines Tages, wer alles da war.' },
      ],
      etapes: [
        { t: 'Das Plakat dorthin, wo gefeiert wird', s: 'Erstellen Sie das Event in zwei Minuten und drucken Sie das Plakat mit dem QR-Code. Stellen Sie es auf die Tische beim Essen oder zum Sektempfang, nicht in die Kirche oder den Raum der Zeremonie: Fotografiert wird danach, beim Feiern.' },
        { t: 'Ein paar Aufnahmen pro Gast', s: 'Sie legen fest, wie viele Fotos jeder machen darf, zwischen 3 und 15. Die Bilder gehen direkt ins Album und lassen sich nicht mehr ansehen, wie bei einer echten Einwegkamera. So wählt jeder seine Momente bewusst.' },
        { t: 'Die Präsentation am Abend oder am nächsten Tag', s: 'Planen Sie die Präsentation für denselben Abend, wenn alle zu Hause sind, oder für den nächsten Morgen. Die Gäste bekommen einen Link und entdecken das Album im selben Moment wie Sie.' },
      ],
      ideesTitre: 'Ideen für die Tauffeier: Fotos mit den Gästen',
      ideesSous: 'Einfache Ideen, die wenig Vorbereitung brauchen und das Album zu einer echten Familienerinnerung machen.',
      idees: [
        { t: 'Das Foto mit den Paten', s: 'Auf dieses Bild warten alle, und genau das fehlt oft. Geben Sie die Aufgabe gleich zu Beginn des Essens einem bestimmten Gast: Patin, Pate und Kind von vorn, danach eines ganz locker. Wenn mehrere Handys dabei sind, ist sicher ein gutes Foto dabei.' },
        { t: 'Vier Generationen', s: 'Wenn Urgroßmutter, Großmutter, Elternteil und Kind zusammen sind, entsteht ein Foto, das sich nicht wiederholen lässt. Planen Sie einen ruhigen Moment ein, einen Stuhl für die Älteste, und lassen Sie mehrere Gäste aus verschiedenen Blickwinkeln fotografieren.' },
        { t: 'Jeder Gast mit dem Baby', s: 'Verkünden Sie die Regel beim Nachtisch: Jeder hebt sich eine Aufnahme für ein Foto mit dem Kind im Arm oder auf dem Schoß auf. Bei der Präsentation haben Sie ein Porträt Ihres Kindes mit jedem einzelnen Gast. Denken Sie an Pausen: Ein müdes Baby geht vor.' },
        { t: 'Das Gästebuch aus Fotos', s: 'Statt eines Gästebuchs mit einem hastigen Satz lassen Sie die Fotos nach der Präsentation drucken und bitten die Familie beim nächsten Besuch, etwas auf die Rückseite zu schreiben. Die Abzüge bestellen Sie direkt aus dem Album, und das Gästebuch entsteht aus den Bildern des Tages.' },
        { t: 'Eine Botschaft zum 18. Geburtstag', s: 'Legen Sie an jeden Platz eine kleine Karte: „Ein paar Worte zu deinem 18.“. Jeder Gast schreibt sie und fotografiert sie dann mit seiner Kamera, unter seinem eigenen Namen. Die Karten kommen in eine Kiste, die Ihr Kind viel später öffnet, und das Album bewahrt eine Kopie.' },
        { t: 'Der Kindertisch', s: 'Cousinen, Cousins und die Kinder von Freunden sitzen oft an einem eigenen Tisch. Geben Sie ihnen ein oder zwei Handys mit ein paar Aufnahmen: Sie fotografieren aus ihrer Höhe, was Erwachsene übersehen. Oft sind das die lustigsten Bilder im Album.' },
        { t: 'Seifenblasen für alle', s: 'Verteilen Sie beim Verlassen der Kirche oder zum Kuchen kleine Seifenblasenfläschchen. Das sieht schön aus, ist für das Baby ungefährlich und ein perfekter Moment, um ihn von allen Seiten gleichzeitig festzuhalten.' },
        { t: 'Der Einweg-Look mit Datum', s: 'Probieren Sie im Album den Film „Einweg“: warme Farben, Körnung und das Datum in der Ecke. Bei einer Taufe bekommt dieses Datum eine besondere Bedeutung: Es ist genau das, was Ihr Kind später in seinen Alben wiederfindet, und es bleibt in den heruntergeladenen Fotos erhalten.' },
      ],
      conseilsTitre: 'Unsere Tipps für ein gelungenes Taufalbum',
      conseils: [
        'Den Ort der Zeremonie respektieren. Ob in der Kirche oder bei einer freien Namensfeier: Die Zeremonie ist ein stiller Moment, und wer sie leitet, bittet vielleicht darum, nicht zu fotografieren. Sagen Sie einfach, dass die Kamera erst danach zum Einsatz kommt, und stellen Sie das Plakat nur dort auf, wo gefeiert wird. Dann kommen die Gäste mit allen Aufnahmen zur Feier.',
        'Wie viele Aufnahmen, und wann präsentieren? Bei einer Taufe reichen 5 bis 8 Aufnahmen pro Person: Der Tag ist ruhiger als eine Party am Abend, und jedes Foto zählt mehr. Nach einem Mittagessen präsentieren Sie das Album am selben Abend gegen 20 Uhr; zieht sich die Feier bis in den Abend, am nächsten Morgen. Hat ein Großelternteil alles zu schnell verbraucht, können Sie den Film nachladen.',
        'Welches Paket? Zu einer Taufe kommen meist 20 bis 60 Personen. Bis 30 Gäste reicht das Paket für 4,99 €, bis 50 Gäste sind es 14,99 €, darüber kostet das Paket für 100 Gäste 29,99 €. Sie zahlen einmal, ohne Abo. Mit 5 Personen können Sie es vorher kostenlos testen, ohne Kreditkarte.',
      ],
      faq: [
        { q: 'Kommen die Großeltern damit zurecht?', a: 'Ja. Sie scannen den QR-Code mit der Handykamera, geben ihren Vornamen ein und drücken auf einen Knopf. Keine App, kein Konto. Wer beim Scannen hängen bleibt, lässt sich einmal von einem Enkelkind helfen, danach geht alles von allein.' },
        { q: 'Passt das auch zu einer freien Namensfeier?', a: 'Auf jeden Fall. Die Kamera hängt nicht von der Zeremonie ab: Sie wird bei der Feier danach genutzt, ob nach einer kirchlichen Taufe, einer freien Namensfeier oder einem einfachen Willkommensfest für das Baby.' },
        { q: 'Was kostet das für eine Taufe?', a: 'Bis 5 Personen ist es kostenlos. Danach zahlen Sie einmalig je nach Gästezahl: 4,99 € für 30, 14,99 € für 50, 29,99 € für 100. Kein Abo, und der Download aller Fotos ist inklusive.' },
        { q: 'Bleiben die Fotos unseres Kindes privat?', a: 'Ja. Das Album ist nie öffentlich: Nur wer den Link hat, kann es sehen. Es wird in Europa gespeichert und nach 6 Monaten gelöscht, und Sie werden vorher benachrichtigt. Laden Sie die Fotos also rechtzeitig herunter. Vor der Präsentation können Sie außerdem jedes Foto ausblenden, das Sie nicht teilen möchten.' },
        { q: 'Können wir danach ein Fotobuch oder Abzüge machen?', a: 'Ja. Sie können alle Fotos herunterladen und daraus ein Fotobuch gestalten oder Abzüge direkt aus dem Album bestellen. Ein schönes Geschenk für die Paten oder die Großeltern.' },
      ],
      ctaTitre: 'Bewahren Sie den ganzen Tag für Ihr Kind',
      ctaSous: 'Richten Sie die Kamera für die Taufe in zwei Minuten ein. Bis 5 Gäste kostenlos.',
    },
  },
}
